// ========== CUPOS POR GRUPO+MATERIA (generado desde cupos.csv) ==========
// Foto de ocupabilidad al momento de la reinscripcion. Editable: corrige cupos.csv y corre build.ps1.
const CUPOS = [
  { g:"7CX1", m:"TRABAJO TERMINAL I", cupo:255, ins:0, disp:255 },
  { g:"8CX1", m:"TRABAJO TERMINAL II", cupo:255, ins:0, disp:255 },
  { g:"7CX2", m:"TRABAJO TERMINAL I", cupo:100, ins:0, disp:100 },
  { g:"8CX2", m:"ESTANCIA PROFESIONAL", cupo:255, ins:177, disp:78 },
  { g:"8CX2", m:"TRABAJO TERMINAL II", cupo:50, ins:0, disp:50 },
  { g:"4CM5", m:"DISEÑO DE SISTEMAS DIGITALES", cupo:36, ins:0, disp:36 },
  { g:"4CM5", m:"SISTEMAS OPERATIVOS", cupo:36, ins:0, disp:36 },
  { g:"4CV1", m:"MATEMATICAS AVANZADAS PARA LA INGENIERIA", cupo:36, ins:2, disp:34 },
  { g:"8CM5", m:"GESTION EMPRESARIAL", cupo:36, ins:2, disp:34 },
  { g:"8CM5", m:"DESARROLLO DE HABILIDADES SOCIALES PARA LA ALTA DIRECCION", cupo:36, ins:2, disp:34 },
  { g:"4CM2", m:"TEORIA DE LA COMPUTACION", cupo:36, ins:4, disp:32 },
  { g:"3CV3", m:"ANALISIS Y DISEÑO DE ALGORITMOS", cupo:36, ins:5, disp:31 },
  { g:"4CV5", m:"PROBABILIDAD Y ESTADISTICA", cupo:36, ins:7, disp:29 },
  { g:"6CX1", m:"ALGORITMOS BIOINSPIRADOS|GENETIC ALGORITHMS", cupo:30, ins:1, disp:29 },
  { g:"7CV3", m:"ALGORITMOS BIOINSPIRADOS|BIOINFORMATICS", cupo:36, ins:7, disp:29 },
  { g:"1CM8", m:"MATEMATICAS DISCRETAS", cupo:36, ins:8, disp:28 },
  { g:"5CM3", m:"INSTRUMENTACION Y CONTROL", cupo:36, ins:8, disp:28 },
  { g:"6CX1", m:"PROC. DE LENG. NAT|MACHINE LEARNING", cupo:30, ins:2, disp:28 },
  { g:"2CV3", m:"MECANICA Y ELECTROMAGNETISMO", cupo:36, ins:9, disp:27 },
  { g:"6CM2", m:"INGENIERIA DE SOFTWARE", cupo:36, ins:9, disp:27 },
  { g:"7CM5", m:"DESARROLLO DE APLICACIONES MOVILES NATIVAS", cupo:36, ins:9, disp:27 },
  { g:"2CV2", m:"CALCULO APLICADO", cupo:36, ins:10, disp:26 },
  { g:"6CX1", m:"BIG DATA|NON-RELATIONAL DATABASES", cupo:30, ins:4, disp:26 },
  { g:"6CX1", m:"TOPICOS SEL. DE COM|COMPUTIG SELECTED TOPICS I", cupo:30, ins:4, disp:26 },
  { g:"3CV1", m:"FUNDAMENTOS DE DISEÑO DIGITAL", cupo:36, ins:11, disp:25 },
  { g:"3CV2", m:"ECUACIONES DIFERENCIALES", cupo:36, ins:11, disp:25 },
  { g:"5CM3", m:"REDES DE COMPUTADORAS", cupo:36, ins:11, disp:25 },
  { g:"5CV1", m:"COMPILADORES", cupo:36, ins:11, disp:25 },
  { g:"5CV2", m:"FORMULACION Y EVALUACION DE PROYECTOS INFORMATICOS", cupo:36, ins:11, disp:25 },
  { g:"7CM6", m:"GOBIERNO DE TI|IT GOVERNANCE", cupo:36, ins:11, disp:25 },
  { g:"4CM1", m:"TEORIA DE LA COMPUTACION", cupo:36, ins:13, disp:23 },
  { g:"4CM2", m:"TECNOLOGIAS PARA DESARROLLO DE APLICACIONES WEB", cupo:36, ins:14, disp:22 },
  { g:"4CV4", m:"MATEMATICAS AVANZADAS PARA LA INGENIERIA", cupo:36, ins:14, disp:22 },
  { g:"6CV4", m:"APLICACIONES PARA COMUNICACIONES EN RED", cupo:36, ins:14, disp:22 },
  { g:"6CX1", m:"GOBIERNO DE TI|COMPUTER SECURITY", cupo:30, ins:8, disp:22 },
  { g:"4CM3", m:"MATEMATICAS AVANZADAS PARA LA INGENIERIA", cupo:36, ins:15, disp:21 },
  { g:"4CV3", m:"ELECTRONICA ANALOGICA", cupo:36, ins:15, disp:21 },
  { g:"3CM2", m:"ECUACIONES DIFERENCIALES", cupo:36, ins:16, disp:20 },
  { g:"7CM3", m:"SISTEMAS DISTRIBUIDOS", cupo:36, ins:16, disp:20 },
  { g:"1CV2", m:"CALCULO", cupo:36, ins:17, disp:19 },
  { g:"2CV3", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:36, ins:17, disp:19 },
  { g:"3CM1", m:"BASES DE DATOS", cupo:36, ins:17, disp:19 },
  { g:"3CV5", m:"FINANZAS EMPRESARIALES", cupo:36, ins:17, disp:19 },
  { g:"7CX1", m:"BIG DATA|BIG DATA", cupo:20, ins:1, disp:19 },
  { g:"7CX1", m:"INTERNET DE LAS COSAS|INTERNET OF THINGS", cupo:20, ins:1, disp:19 },
  { g:"7CX1", m:"CRIPTOGRAFIA|SELECTED TOPICS IN CRYPTOGRAPHY", cupo:20, ins:1, disp:19 },
  { g:"7CX1", m:"ALGORITMOS BIOINSPIRADOS|BIOINFORMATICS", cupo:20, ins:1, disp:19 },
  { g:"8CM3", m:"DESARROLLO DE HABILIDADES SOCIALES PARA LA ALTA DIRECCION", cupo:36, ins:17, disp:19 },
  { g:"1CV5", m:"MATEMATICAS DISCRETAS", cupo:36, ins:18, disp:18 },
  { g:"2CV1", m:"CALCULO APLICADO", cupo:36, ins:18, disp:18 },
  { g:"2CV5", m:"ALGEBRA LINEAL", cupo:36, ins:18, disp:18 },
  { g:"3CM5", m:"ECUACIONES DIFERENCIALES", cupo:36, ins:18, disp:18 },
  { g:"4CV2", m:"SISTEMAS OPERATIVOS", cupo:36, ins:18, disp:18 },
  { g:"7CM2", m:"INSTRUMENTAL VIRTUAL|VIRTUAL INSTRUMENTIATION APPLICATIONS", cupo:36, ins:18, disp:18 },
  { g:"7CM2", m:"ADMINISTRACION DE SERVICIOS EN RED", cupo:30, ins:12, disp:18 },
  { g:"7CX1", m:"GOBIERNO DE TI|IT GOVERNANCE", cupo:20, ins:2, disp:18 },
  { g:"7CX1", m:"VISION POR COMPUTADORA|IMAGE ANALYSIS", cupo:20, ins:2, disp:18 },
  { g:"8CV3", m:"TRABAJO TERMINAL II", cupo:36, ins:18, disp:18 },
  { g:"3CV2", m:"CIRCUITOS ELECTRICOS", cupo:36, ins:19, disp:17 },
  { g:"3CV4", m:"FUNDAMENTOS DE DISEÑO DIGITAL", cupo:36, ins:19, disp:17 },
  { g:"3CV4", m:"CIRCUITOS ELECTRICOS", cupo:36, ins:19, disp:17 },
  { g:"6CM2", m:"INTELIGENCIA ARTIFICIAL", cupo:36, ins:19, disp:17 },
  { g:"2CV2", m:"INGENIERIA ETICA Y SOCIEDAD", cupo:36, ins:20, disp:16 },
  { g:"2CV3", m:"FUNDAMENTOS ECONOMICOS", cupo:36, ins:20, disp:16 },
  { g:"3CM5", m:"BASES DE DATOS", cupo:36, ins:20, disp:16 },
  { g:"7CM3", m:"VISION POR COMPUTADORA|IMAGE ANALYSIS", cupo:30, ins:14, disp:16 },
  { g:"7CV5", m:"MINERIA DE DATOS|DATA MINING", cupo:36, ins:20, disp:16 },
  { g:"7CX1", m:"PROC. DE LENG|NATURAL LANGUAGE PROCESSING", cupo:20, ins:4, disp:16 },
  { g:"8CM5", m:"TRABAJO TERMINAL II", cupo:36, ins:20, disp:16 },
  { g:"1CV1", m:"MATEMATICAS DISCRETAS", cupo:36, ins:21, disp:15 },
  { g:"4CM5", m:"ELECTRONICA ANALOGICA", cupo:36, ins:21, disp:15 },
  { g:"5CV1", m:"FORMULACION Y EVALUACION DE PROYECTOS INFORMATICOS", cupo:36, ins:21, disp:15 },
  { g:"6CM4", m:"PROC. DE LENG. NAT|MACHINE LEARNING", cupo:36, ins:21, disp:15 },
  { g:"7CM4", m:"SISTEMAS COMPLEJOS|COMPLEX SYSTEMS", cupo:36, ins:21, disp:15 },
  { g:"7CM4", m:"GES. DE EMP. DE ALTA TEC|ECONOMIC ENGINEERING", cupo:35, ins:20, disp:15 },
  { g:"8CV4", m:"TRABAJO TERMINAL II", cupo:34, ins:19, disp:15 },
  { g:"1CM10", m:"CALCULO", cupo:36, ins:22, disp:14 },
  { g:"4CM1", m:"PROBABILIDAD Y ESTADISTICA", cupo:36, ins:22, disp:14 },
  { g:"4CM2", m:"ELECTRONICA ANALOGICA", cupo:36, ins:22, disp:14 },
  { g:"5CM1", m:"INSTRUMENTACION Y CONTROL", cupo:30, ins:16, disp:14 },
  { g:"7CM3", m:"DESARROLLO DE APLICACIONES MOVILES NATIVAS", cupo:36, ins:22, disp:14 },
  { g:"7CM4", m:"DESARROLLO DE APLICACIONES MOVILES NATIVAS", cupo:36, ins:22, disp:14 },
  { g:"7CX1", m:"TOPICOS SEL. DE COM|COMPUTING SELECTED TOPICS II", cupo:20, ins:6, disp:14 },
  { g:"1CX1", m:"CALCULO", cupo:30, ins:17, disp:13 },
  { g:"4CV3", m:"PROBABILIDAD Y ESTADISTICA", cupo:36, ins:23, disp:13 },
  { g:"5CM5", m:"COMPILADORES", cupo:36, ins:23, disp:13 },
  { g:"6CV3", m:"APLICACIONES PARA COMUNICACIONES EN RED", cupo:36, ins:23, disp:13 },
  { g:"8CM2", m:"DESARROLLO DE HABILIDADES SOCIALES PARA LA ALTA DIRECCION", cupo:36, ins:23, disp:13 },
  { g:"2CM6", m:"MECANICA Y ELECTROMAGNETISMO", cupo:36, ins:24, disp:12 },
  { g:"3CM3", m:"PARADIGMAS DE PROGRAMACION", cupo:36, ins:24, disp:12 },
  { g:"3CV4", m:"BASES DE DATOS", cupo:36, ins:24, disp:12 },
  { g:"4CV4", m:"ELECTRONICA ANALOGICA", cupo:36, ins:25, disp:11 },
  { g:"5CV3", m:"FORMULACION Y EVALUACION DE PROYECTOS INFORMATICOS", cupo:36, ins:25, disp:11 },
  { g:"5CV4", m:"COMPILADORES", cupo:36, ins:25, disp:11 },
  { g:"8CM3", m:"TRABAJO TERMINAL II", cupo:36, ins:25, disp:11 },
  { g:"1CV3", m:"CALCULO", cupo:36, ins:26, disp:10 },
  { g:"2CX1", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:20, ins:10, disp:10 },
  { g:"3CV3", m:"CIRCUITOS ELECTRICOS", cupo:36, ins:26, disp:10 },
  { g:"7CM5", m:"MINERIA DE DATOS|DATA MINING", cupo:35, ins:25, disp:10 },
  { g:"7CV4", m:"TRABAJO TERMINAL I", cupo:36, ins:26, disp:10 },
  { g:"8CM3", m:"LIDERAZGO PERSONAL", cupo:36, ins:26, disp:10 },
  { g:"3CV1", m:"ECUACIONES DIFERENCIALES", cupo:36, ins:27, disp:9 },
  { g:"3CV3", m:"BASES DE DATOS", cupo:36, ins:27, disp:9 },
  { g:"7CM2", m:"SISTEMAS DISTRIBUIDOS", cupo:36, ins:27, disp:9 },
  { g:"7CV2", m:"TRABAJO TERMINAL I", cupo:36, ins:27, disp:9 },
  { g:"8CM4", m:"LIDERAZGO PERSONAL", cupo:33, ins:24, disp:9 },
  { g:"1CV1", m:"CALCULO", cupo:36, ins:28, disp:8 },
  { g:"2CM1", m:"MECANICA Y ELECTROMAGNETISMO", cupo:36, ins:28, disp:8 },
  { g:"3CV1", m:"CIRCUITOS ELECTRICOS", cupo:36, ins:28, disp:8 },
  { g:"4CV2", m:"TEORIA DE LA COMPUTACION", cupo:36, ins:28, disp:8 },
  { g:"4CV3", m:"MATEMATICAS AVANZADAS PARA LA INGENIERIA", cupo:36, ins:28, disp:8 },
  { g:"4CV4", m:"DISEÑO DE SISTEMAS DIGITALES", cupo:36, ins:28, disp:8 },
  { g:"5CV2", m:"ARQUITECTURA DE COMPUTADORAS", cupo:35, ins:27, disp:8 },
  { g:"6CV1", m:"APLICACIONES PARA COMUNICACIONES EN RED", cupo:34, ins:26, disp:8 },
  { g:"7CM1", m:"CRIPTOGRAFIA|SELECTED TOPICS IN CRYPTOGRAPHY", cupo:36, ins:28, disp:8 },
  { g:"8CM2", m:"GESTION EMPRESARIAL", cupo:33, ins:25, disp:8 },
  { g:"1CV4", m:"CALCULO", cupo:36, ins:29, disp:7 },
  { g:"2CM2", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:36, ins:29, disp:7 },
  { g:"2CV2", m:"FUNDAMENTOS ECONOMICOS", cupo:36, ins:29, disp:7 },
  { g:"3CM4", m:"ECUACIONES DIFERENCIALES", cupo:36, ins:29, disp:7 },
  { g:"3CV4", m:"FINANZAS EMPRESARIALES", cupo:36, ins:29, disp:7 },
  { g:"4CM3", m:"PROBABILIDAD Y ESTADISTICA", cupo:36, ins:29, disp:7 },
  { g:"5CV2", m:"PROCESAMIENTO DIGITAL DE SEÑALES", cupo:34, ins:27, disp:7 },
  { g:"7CM1", m:"INTERNET DE LAS COSAS|INTERNET OF THINGS", cupo:36, ins:29, disp:7 },
  { g:"2CV1", m:"MECANICA Y ELECTROMAGNETISMO", cupo:36, ins:30, disp:6 },
  { g:"2CV2", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:36, ins:30, disp:6 },
  { g:"3CM3", m:"ANALISIS Y DISEÑO DE ALGORITMOS", cupo:36, ins:30, disp:6 },
  { g:"3CM5", m:"FINANZAS EMPRESARIALES", cupo:36, ins:30, disp:6 },
  { g:"5CM2", m:"REDES DE COMPUTADORAS", cupo:36, ins:30, disp:6 },
  { g:"1CM7", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:31, disp:5 },
  { g:"1CV3", m:"COMUNICACION ORAL Y ESCRITA", cupo:36, ins:31, disp:5 },
  { g:"2CM3", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:36, ins:31, disp:5 },
  { g:"3CV2", m:"FINANZAS EMPRESARIALES", cupo:36, ins:31, disp:5 },
  { g:"4CM1", m:"DISEÑO DE SISTEMAS DIGITALES", cupo:36, ins:31, disp:5 },
  { g:"4CV2", m:"PROBABILIDAD Y ESTADISTICA", cupo:36, ins:31, disp:5 },
  { g:"5CM5", m:"ARQUITECTURA DE COMPUTADORAS", cupo:36, ins:31, disp:5 },
  { g:"6CM2", m:"METODOS CUANTITATIVOS PARA LA TOMA DE DECISIONES", cupo:36, ins:31, disp:5 },
  { g:"7CM2", m:"TRABAJO TERMINAL I", cupo:36, ins:31, disp:5 },
  { g:"8CV2", m:"TRABAJO TERMINAL II", cupo:36, ins:31, disp:5 },
  { g:"1CM6", m:"COMUNICACION ORAL Y ESCRITA", cupo:36, ins:32, disp:4 },
  { g:"2CV4", m:"CALCULO APLICADO", cupo:36, ins:32, disp:4 },
  { g:"3CM2", m:"PARADIGMAS DE PROGRAMACION", cupo:36, ins:32, disp:4 },
  { g:"3CV1", m:"ANALISIS Y DISEÑO DE ALGORITMOS", cupo:36, ins:32, disp:4 },
  { g:"4CM4", m:"TEORIA DE LA COMPUTACION", cupo:36, ins:32, disp:4 },
  { g:"4CV3", m:"SISTEMAS OPERATIVOS", cupo:36, ins:32, disp:4 },
  { g:"5CV2", m:"INSTRUMENTACION Y CONTROL", cupo:36, ins:32, disp:4 },
  { g:"6CV2", m:"APLICACIONES PARA COMUNICACIONES EN RED", cupo:36, ins:32, disp:4 },
  { g:"7CM3", m:"TRABAJO TERMINAL I", cupo:36, ins:32, disp:4 },
  { g:"8CV2", m:"GESTION EMPRESARIAL", cupo:36, ins:32, disp:4 },
  { g:"1CM2", m:"CALCULO", cupo:36, ins:33, disp:3 },
  { g:"1CM7", m:"CALCULO", cupo:36, ins:33, disp:3 },
  { g:"1CV2", m:"COMUNICACION ORAL Y ESCRITA", cupo:36, ins:33, disp:3 },
  { g:"1CV3", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:33, disp:3 },
  { g:"1CV4", m:"ANALISIS VECTORIAL", cupo:36, ins:33, disp:3 },
  { g:"2CM3", m:"MECANICA Y ELECTROMAGNETISMO", cupo:36, ins:33, disp:3 },
  { g:"2CM5", m:"MECANICA Y ELECTROMAGNETISMO", cupo:36, ins:33, disp:3 },
  { g:"5CM1", m:"ARQUITECTURA DE COMPUTADORAS", cupo:36, ins:33, disp:3 },
  { g:"5CV3", m:"ARQUITECTURA DE COMPUTADORAS", cupo:36, ins:33, disp:3 },
  { g:"6CM4", m:"INGENIERIA DE SOFTWARE", cupo:36, ins:33, disp:3 },
  { g:"7CM3", m:"DES. DE APLIC|WEB CLIENT AND BACKEND DEVELOPMEN FRAMEWORKS", cupo:36, ins:33, disp:3 },
  { g:"7CM4", m:"SISTEMAS DISTRIBUIDOS", cupo:36, ins:33, disp:3 },
  { g:"8CM3", m:"GESTION EMPRESARIAL", cupo:36, ins:33, disp:3 },
  { g:"8CM4", m:"TRABAJO TERMINAL II", cupo:36, ins:33, disp:3 },
  { g:"8CV1", m:"DESARROLLO DE HABILIDADES SOCIALES PARA LA ALTA DIRECCION", cupo:36, ins:33, disp:3 },
  { g:"8CV2", m:"DESARROLLO DE HABILIDADES SOCIALES PARA LA ALTA DIRECCION", cupo:36, ins:33, disp:3 },
  { g:"1CM1", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:34, disp:2 },
  { g:"1CM1", m:"COMUNICACION ORAL Y ESCRITA", cupo:36, ins:34, disp:2 },
  { g:"1CM2", m:"COMUNICACION ORAL Y ESCRITA", cupo:36, ins:34, disp:2 },
  { g:"1CM3", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:34, disp:2 },
  { g:"1CM3", m:"CALCULO", cupo:36, ins:34, disp:2 },
  { g:"1CM3", m:"COMUNICACION ORAL Y ESCRITA", cupo:36, ins:34, disp:2 },
  { g:"1CM4", m:"COMUNICACION ORAL Y ESCRITA", cupo:36, ins:34, disp:2 },
  { g:"1CM5", m:"CALCULO", cupo:36, ins:34, disp:2 },
  { g:"1CM5", m:"COMUNICACION ORAL Y ESCRITA", cupo:36, ins:34, disp:2 },
  { g:"1CM6", m:"CALCULO", cupo:36, ins:34, disp:2 },
  { g:"1CM6", m:"ANALISIS VECTORIAL", cupo:36, ins:34, disp:2 },
  { g:"1CV5", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:34, disp:2 },
  { g:"1CV5", m:"CALCULO", cupo:36, ins:34, disp:2 },
  { g:"1CV5", m:"ANALISIS VECTORIAL", cupo:36, ins:34, disp:2 },
  { g:"1CV6", m:"MATEMATICAS DISCRETAS", cupo:36, ins:34, disp:2 },
  { g:"2CV2", m:"MECANICA Y ELECTROMAGNETISMO", cupo:36, ins:34, disp:2 },
  { g:"3CM3", m:"FINANZAS EMPRESARIALES", cupo:36, ins:34, disp:2 },
  { g:"3CM4", m:"ANALISIS Y DISEÑO DE ALGORITMOS", cupo:36, ins:34, disp:2 },
  { g:"3CV2", m:"ANALISIS Y DISEÑO DE ALGORITMOS", cupo:36, ins:34, disp:2 },
  { g:"3CV4", m:"ECUACIONES DIFERENCIALES", cupo:36, ins:34, disp:2 },
  { g:"4CM3", m:"DISEÑO DE SISTEMAS DIGITALES", cupo:36, ins:34, disp:2 },
  { g:"4CM5", m:"TECNOLOGIAS PARA DESARROLLO DE APLICACIONES WEB", cupo:36, ins:34, disp:2 },
  { g:"4CV1", m:"DISEÑO DE SISTEMAS DIGITALES", cupo:36, ins:34, disp:2 },
  { g:"5CM1", m:"ANALISIS Y DISEÑO DE SISTEMAS", cupo:36, ins:34, disp:2 },
  { g:"5CV2", m:"ANALISIS Y DISEÑO DE SISTEMAS", cupo:36, ins:34, disp:2 },
  { g:"6CM1", m:"INTELIGENCIA ARTIFICIAL", cupo:35, ins:33, disp:2 },
  { g:"6CM1", m:"METODOS CUANTITATIVOS PARA LA TOMA DE DECISIONES", cupo:36, ins:34, disp:2 },
  { g:"7CM1", m:"DESARROLLO DE APLICACIONES MOVILES NATIVAS", cupo:36, ins:34, disp:2 },
  { g:"7CM1", m:"ADMINISTRACION DE SERVICIOS EN RED", cupo:36, ins:34, disp:2 },
  { g:"7CV3", m:"DESARROLLO DE APLICACIONES MOVILES NATIVAS", cupo:36, ins:34, disp:2 },
  { g:"7CV3", m:"ADMINISTRACION DE SERVICIOS EN RED", cupo:36, ins:34, disp:2 },
  { g:"7CV4", m:"SISTEMAS DISTRIBUIDOS", cupo:36, ins:34, disp:2 },
  { g:"7CV4", m:"BIG DATA|BIG DATA", cupo:36, ins:34, disp:2 },
  { g:"8CM2", m:"TRABAJO TERMINAL II", cupo:36, ins:34, disp:2 },
  { g:"8CM4", m:"GESTION EMPRESARIAL", cupo:34, ins:32, disp:2 },
  { g:"8CV1", m:"TRABAJO TERMINAL II", cupo:36, ins:34, disp:2 },
  { g:"8CV2", m:"LIDERAZGO PERSONAL", cupo:34, ins:32, disp:2 },
  { g:"1CM1", m:"CALCULO", cupo:36, ins:35, disp:1 },
  { g:"1CM2", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:35, disp:1 },
  { g:"1CM3", m:"ANALISIS VECTORIAL", cupo:36, ins:35, disp:1 },
  { g:"1CM5", m:"ANALISIS VECTORIAL", cupo:36, ins:35, disp:1 },
  { g:"1CM6", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:35, disp:1 },
  { g:"1CM6", m:"MATEMATICAS DISCRETAS", cupo:36, ins:35, disp:1 },
  { g:"1CM7", m:"MATEMATICAS DISCRETAS", cupo:36, ins:35, disp:1 },
  { g:"1CM7", m:"ANALISIS VECTORIAL", cupo:36, ins:35, disp:1 },
  { g:"1CV1", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:35, disp:1 },
  { g:"1CV3", m:"MATEMATICAS DISCRETAS", cupo:36, ins:35, disp:1 },
  { g:"1CV4", m:"MATEMATICAS DISCRETAS", cupo:36, ins:35, disp:1 },
  { g:"1CV4", m:"COMUNICACION ORAL Y ESCRITA", cupo:36, ins:35, disp:1 },
  { g:"1CV6", m:"CALCULO", cupo:36, ins:35, disp:1 },
  { g:"2CM2", m:"CALCULO APLICADO", cupo:36, ins:35, disp:1 },
  { g:"2CM2", m:"MECANICA Y ELECTROMAGNETISMO", cupo:36, ins:35, disp:1 },
  { g:"2CM3", m:"INGENIERIA ETICA Y SOCIEDAD", cupo:36, ins:35, disp:1 },
  { g:"2CM4", m:"ALGEBRA LINEAL", cupo:36, ins:35, disp:1 },
  { g:"2CM5", m:"CALCULO APLICADO", cupo:36, ins:35, disp:1 },
  { g:"2CM5", m:"INGENIERIA ETICA Y SOCIEDAD", cupo:36, ins:35, disp:1 },
  { g:"2CM6", m:"INGENIERIA ETICA Y SOCIEDAD", cupo:36, ins:35, disp:1 },
  { g:"2CM6", m:"FUNDAMENTOS ECONOMICOS", cupo:34, ins:33, disp:1 },
  { g:"2CV1", m:"FUNDAMENTOS ECONOMICOS", cupo:36, ins:35, disp:1 },
  { g:"2CV2", m:"ALGEBRA LINEAL", cupo:37, ins:36, disp:1 },
  { g:"2CV3", m:"ALGEBRA LINEAL", cupo:36, ins:35, disp:1 },
  { g:"2CV3", m:"INGENIERIA ETICA Y SOCIEDAD", cupo:36, ins:35, disp:1 },
  { g:"2CV4", m:"FUNDAMENTOS ECONOMICOS", cupo:36, ins:35, disp:1 },
  { g:"3CM1", m:"ANALISIS Y DISEÑO DE ALGORITMOS", cupo:36, ins:35, disp:1 },
  { g:"3CM2", m:"ANALISIS Y DISEÑO DE ALGORITMOS", cupo:34, ins:33, disp:1 },
  { g:"3CM2", m:"FUNDAMENTOS DE DISEÑO DIGITAL", cupo:36, ins:35, disp:1 },
  { g:"3CV2", m:"PARADIGMAS DE PROGRAMACION", cupo:36, ins:35, disp:1 },
  { g:"3CV3", m:"FUNDAMENTOS DE DISEÑO DIGITAL", cupo:36, ins:35, disp:1 },
  { g:"3CV4", m:"ANALISIS Y DISEÑO DE ALGORITMOS", cupo:36, ins:35, disp:1 },
  { g:"4CM1", m:"MATEMATICAS AVANZADAS PARA LA INGENIERIA", cupo:36, ins:35, disp:1 },
  { g:"4CM3", m:"ELECTRONICA ANALOGICA", cupo:36, ins:35, disp:1 },
  { g:"4CM3", m:"SISTEMAS OPERATIVOS", cupo:36, ins:35, disp:1 },
  { g:"4CM4", m:"TECNOLOGIAS PARA DESARROLLO DE APLICACIONES WEB", cupo:36, ins:35, disp:1 },
  { g:"4CM5", m:"PROBABILIDAD Y ESTADISTICA", cupo:36, ins:35, disp:1 },
  { g:"4CV1", m:"TEORIA DE LA COMPUTACION", cupo:36, ins:35, disp:1 },
  { g:"4CV1", m:"SISTEMAS OPERATIVOS", cupo:36, ins:35, disp:1 },
  { g:"4CV2", m:"TECNOLOGIAS PARA DESARROLLO DE APLICACIONES WEB", cupo:36, ins:35, disp:1 },
  { g:"4CV4", m:"TEORIA DE LA COMPUTACION", cupo:36, ins:35, disp:1 },
  { g:"5CM1", m:"PROCESAMIENTO DIGITAL DE SEÑALES", cupo:34, ins:33, disp:1 },
  { g:"5CM2", m:"ARQUITECTURA DE COMPUTADORAS", cupo:36, ins:35, disp:1 },
  { g:"5CM2", m:"INSTRUMENTACION Y CONTROL", cupo:36, ins:35, disp:1 },
  { g:"5CM6", m:"PROCESAMIENTO DIGITAL DE SEÑALES", cupo:36, ins:35, disp:1 },
  { g:"5CV3", m:"COMPILADORES", cupo:33, ins:32, disp:1 },
  { g:"5CV4", m:"INSTRUMENTACION Y CONTROL", cupo:36, ins:35, disp:1 },
  { g:"6CM1", m:"INGENIERIA DE SOFTWARE", cupo:36, ins:35, disp:1 },
  { g:"6CM2", m:"SISTEMAS EN CHIP", cupo:36, ins:35, disp:1 },
  { g:"6CM3", m:"INTERNET DE LAS COSAS|EMBEDDED SYSTEMS", cupo:36, ins:35, disp:1 },
  { g:"6CM4", m:"SISTEMAS EN CHIP", cupo:36, ins:35, disp:1 },
  { g:"6CM4", m:"APLICACIONES PARA COMUNICACIONES EN RED", cupo:34, ins:33, disp:1 },
  { g:"6CM6", m:"ALGORITMOS BIOINSPIRADOS|GENETIC ALGORITHMS", cupo:1, ins:0, disp:1 },
  { g:"6CV1", m:"INGENIERIA DE SOFTWARE", cupo:36, ins:35, disp:1 },
  { g:"6CV2", m:"INGENIERIA DE SOFTWARE", cupo:36, ins:35, disp:1 },
  { g:"6CV3", m:"METODOS CUANTITATIVOS PARA LA TOMA DE DECISIONES", cupo:35, ins:34, disp:1 },
  { g:"6CV3", m:"CRIPTOGRAFIA|INTRODUCTION TO CRYPTOGRAPHY", cupo:36, ins:35, disp:1 },
  { g:"6CV3", m:"INGENIERIA DE SOFTWARE", cupo:34, ins:33, disp:1 },
  { g:"6CV4", m:"SISTEMAS EN CHIP", cupo:34, ins:33, disp:1 },
  { g:"7CM1", m:"TRABAJO TERMINAL I", cupo:36, ins:35, disp:1 },
  { g:"7CM3", m:"ADMINISTRACION DE SERVICIOS EN RED", cupo:36, ins:35, disp:1 },
  { g:"7CM4", m:"TRABAJO TERMINAL I", cupo:36, ins:35, disp:1 },
  { g:"7CV1", m:"SISTEMAS DISTRIBUIDOS", cupo:36, ins:35, disp:1 },
  { g:"7CV1", m:"DESARROLLO DE APLICACIONES MOVILES NATIVAS", cupo:36, ins:35, disp:1 },
  { g:"7CV1", m:"ADMINISTRACION DE SERVICIOS EN RED", cupo:35, ins:34, disp:1 },
  { g:"7CV3", m:"SISTEMAS DISTRIBUIDOS", cupo:36, ins:35, disp:1 },
  { g:"7CV4", m:"ADMINISTRACION DE SERVICIOS EN RED", cupo:36, ins:35, disp:1 },
  { g:"7CV6", m:"ALGORITMOS BIOINSPIRADOS|BIOINFORMATICS", cupo:1, ins:0, disp:1 },
  { g:"8CM1", m:"LIDERAZGO PERSONAL", cupo:35, ins:34, disp:1 },
  { g:"8CM1", m:"DESARROLLO DE HABILIDADES SOCIALES PARA LA ALTA DIRECCION", cupo:36, ins:35, disp:1 },
  { g:"8CM2", m:"LIDERAZGO PERSONAL", cupo:36, ins:35, disp:1 },
  { g:"8CM4", m:"DESARROLLO DE HABILIDADES SOCIALES PARA LA ALTA DIRECCION", cupo:36, ins:35, disp:1 },
  { g:"8CV1", m:"GESTION EMPRESARIAL", cupo:34, ins:33, disp:1 },
  { g:"1CM2", m:"MATEMATICAS DISCRETAS", cupo:36, ins:36, disp:0 },
  { g:"1CM2", m:"ANALISIS VECTORIAL", cupo:36, ins:36, disp:0 },
  { g:"1CM3", m:"MATEMATICAS DISCRETAS", cupo:36, ins:36, disp:0 },
  { g:"1CM4", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:36, disp:0 },
  { g:"1CM4", m:"MATEMATICAS DISCRETAS", cupo:36, ins:36, disp:0 },
  { g:"1CM4", m:"CALCULO", cupo:36, ins:36, disp:0 },
  { g:"1CM5", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:36, disp:0 },
  { g:"1CM5", m:"MATEMATICAS DISCRETAS", cupo:36, ins:36, disp:0 },
  { g:"1CM8", m:"CALCULO", cupo:36, ins:36, disp:0 },
  { g:"1CV1", m:"ANALISIS VECTORIAL", cupo:36, ins:36, disp:0 },
  { g:"1CV1", m:"COMUNICACION ORAL Y ESCRITA", cupo:36, ins:36, disp:0 },
  { g:"1CV2", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:36, disp:0 },
  { g:"1CV2", m:"MATEMATICAS DISCRETAS", cupo:36, ins:36, disp:0 },
  { g:"1CV2", m:"ANALISIS VECTORIAL", cupo:36, ins:36, disp:0 },
  { g:"1CV3", m:"ANALISIS VECTORIAL", cupo:36, ins:36, disp:0 },
  { g:"1CV5", m:"COMUNICACION ORAL Y ESCRITA", cupo:36, ins:36, disp:0 },
  { g:"1CV6", m:"ANALISIS VECTORIAL", cupo:36, ins:36, disp:0 },
  { g:"2CM1", m:"CALCULO APLICADO", cupo:36, ins:36, disp:0 },
  { g:"2CM1", m:"INGENIERIA ETICA Y SOCIEDAD", cupo:36, ins:36, disp:0 },
  { g:"2CM1", m:"FUNDAMENTOS ECONOMICOS", cupo:36, ins:36, disp:0 },
  { g:"2CM2", m:"ALGEBRA LINEAL", cupo:36, ins:36, disp:0 },
  { g:"2CM2", m:"FUNDAMENTOS ECONOMICOS", cupo:36, ins:36, disp:0 },
  { g:"2CM3", m:"FUNDAMENTOS ECONOMICOS", cupo:36, ins:36, disp:0 },
  { g:"2CM4", m:"INGENIERIA ETICA Y SOCIEDAD", cupo:36, ins:36, disp:0 },
  { g:"2CM5", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:36, ins:36, disp:0 },
  { g:"2CM5", m:"FUNDAMENTOS ECONOMICOS", cupo:36, ins:36, disp:0 },
  { g:"2CM6", m:"ALGEBRA LINEAL", cupo:36, ins:36, disp:0 },
  { g:"2CV1", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:36, ins:36, disp:0 },
  { g:"2CV1", m:"ALGEBRA LINEAL", cupo:36, ins:36, disp:0 },
  { g:"2CV3", m:"CALCULO APLICADO", cupo:36, ins:36, disp:0 },
  { g:"2CV4", m:"MECANICA Y ELECTROMAGNETISMO", cupo:36, ins:36, disp:0 },
  { g:"2CV4", m:"INGENIERIA ETICA Y SOCIEDAD", cupo:36, ins:36, disp:0 },
  { g:"2CV5", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:36, ins:36, disp:0 },
  { g:"2CV5", m:"CALCULO APLICADO", cupo:36, ins:36, disp:0 },
  { g:"2CV5", m:"MECANICA Y ELECTROMAGNETISMO", cupo:36, ins:36, disp:0 },
  { g:"2CV5", m:"INGENIERIA ETICA Y SOCIEDAD", cupo:36, ins:36, disp:0 },
  { g:"2CV5", m:"FUNDAMENTOS ECONOMICOS", cupo:36, ins:36, disp:0 },
  { g:"2CV6", m:"ALGEBRA LINEAL", cupo:36, ins:36, disp:0 },
  { g:"3CM1", m:"PARADIGMAS DE PROGRAMACION", cupo:36, ins:36, disp:0 },
  { g:"3CM1", m:"CIRCUITOS ELECTRICOS", cupo:36, ins:36, disp:0 },
  { g:"3CM2", m:"CIRCUITOS ELECTRICOS", cupo:36, ins:36, disp:0 },
  { g:"3CM2", m:"FINANZAS EMPRESARIALES", cupo:36, ins:36, disp:0 },
  { g:"3CM3", m:"ECUACIONES DIFERENCIALES", cupo:36, ins:36, disp:0 },
  { g:"3CM4", m:"FUNDAMENTOS DE DISEÑO DIGITAL", cupo:36, ins:36, disp:0 },
  { g:"3CM4", m:"CIRCUITOS ELECTRICOS", cupo:36, ins:36, disp:0 },
  { g:"3CM4", m:"FINANZAS EMPRESARIALES", cupo:36, ins:36, disp:0 },
  { g:"3CM5", m:"PARADIGMAS DE PROGRAMACION", cupo:36, ins:36, disp:0 },
  { g:"3CM5", m:"FUNDAMENTOS DE DISEÑO DIGITAL", cupo:36, ins:36, disp:0 },
  { g:"3CM5", m:"CIRCUITOS ELECTRICOS", cupo:36, ins:36, disp:0 },
  { g:"3CV2", m:"BASES DE DATOS", cupo:36, ins:36, disp:0 },
  { g:"3CV3", m:"PARADIGMAS DE PROGRAMACION", cupo:36, ins:36, disp:0 },
  { g:"3CV3", m:"ECUACIONES DIFERENCIALES", cupo:36, ins:36, disp:0 },
  { g:"3CV3", m:"FINANZAS EMPRESARIALES", cupo:36, ins:36, disp:0 },
  { g:"3CV5", m:"PARADIGMAS DE PROGRAMACION", cupo:36, ins:36, disp:0 },
  { g:"4CM1", m:"ELECTRONICA ANALOGICA", cupo:36, ins:36, disp:0 },
  { g:"4CM1", m:"TECNOLOGIAS PARA DESARROLLO DE APLICACIONES WEB", cupo:36, ins:36, disp:0 },
  { g:"4CM1", m:"SISTEMAS OPERATIVOS", cupo:36, ins:36, disp:0 },
  { g:"4CM2", m:"DISEÑO DE SISTEMAS DIGITALES", cupo:36, ins:36, disp:0 },
  { g:"4CM3", m:"TECNOLOGIAS PARA DESARROLLO DE APLICACIONES WEB", cupo:36, ins:36, disp:0 },
  { g:"4CM4", m:"MATEMATICAS AVANZADAS PARA LA INGENIERIA", cupo:36, ins:36, disp:0 },
  { g:"4CM4", m:"DISEÑO DE SISTEMAS DIGITALES", cupo:34, ins:34, disp:0 },
  { g:"4CM4", m:"ELECTRONICA ANALOGICA", cupo:36, ins:36, disp:0 },
  { g:"4CM4", m:"SISTEMAS OPERATIVOS", cupo:35, ins:35, disp:0 },
  { g:"4CM5", m:"MATEMATICAS AVANZADAS PARA LA INGENIERIA", cupo:36, ins:36, disp:0 },
  { g:"4CV3", m:"TEORIA DE LA COMPUTACION", cupo:36, ins:36, disp:0 },
  { g:"4CV4", m:"TECNOLOGIAS PARA DESARROLLO DE APLICACIONES WEB", cupo:36, ins:36, disp:0 },
  { g:"5CM1", m:"COMPILADORES", cupo:36, ins:36, disp:0 },
  { g:"5CM1", m:"FORMULACION Y EVALUACION DE PROYECTOS INFORMATICOS", cupo:36, ins:36, disp:0 },
  { g:"5CM3", m:"ANALISIS Y DISEÑO DE SISTEMAS", cupo:36, ins:36, disp:0 },
  { g:"5CM4", m:"ARQUITECTURA DE COMPUTADORAS", cupo:36, ins:36, disp:0 },
  { g:"5CM4", m:"INSTRUMENTACION Y CONTROL", cupo:36, ins:36, disp:0 },
  { g:"5CM4", m:"REDES DE COMPUTADORAS", cupo:36, ins:36, disp:0 },
  { g:"5CV1", m:"INSTRUMENTACION Y CONTROL", cupo:36, ins:36, disp:0 },
  { g:"5CV3", m:"REDES DE COMPUTADORAS", cupo:36, ins:36, disp:0 },
  { g:"5CV4", m:"ANALISIS Y DISEÑO DE SISTEMAS", cupo:36, ins:36, disp:0 },
  { g:"5CV4", m:"FORMULACION Y EVALUACION DE PROYECTOS INFORMATICOS", cupo:36, ins:36, disp:0 },
  { g:"5CV4", m:"REDES DE COMPUTADORAS", cupo:36, ins:36, disp:0 },
  { g:"6CM2", m:"DES. DE APLIC|SOFTWARE QUALLITY ASSURANCE AND DESING PATTERNS", cupo:36, ins:36, disp:0 },
  { g:"6CM2", m:"APLICACIONES PARA COMUNICACIONES EN RED", cupo:36, ins:36, disp:0 },
  { g:"6CM3", m:"INTELIGENCIA ARTIFICIAL", cupo:36, ins:36, disp:0 },
  { g:"6CM3", m:"SISTEMAS EN CHIP", cupo:34, ins:34, disp:0 },
  { g:"6CM3", m:"APLICACIONES PARA COMUNICACIONES EN RED", cupo:36, ins:36, disp:0 },
  { g:"6CM4", m:"INTELIGENCIA ARTIFICIAL", cupo:36, ins:36, disp:0 },
  { g:"6CM6", m:"GOBIERNO DE TI|COMPUTER SECURITY", cupo:1, ins:1, disp:0 },
  { g:"6CV3", m:"INTELIGENCIA ARTIFICIAL", cupo:36, ins:36, disp:0 },
  { g:"6CV3", m:"SISTEMAS EN CHIP", cupo:36, ins:36, disp:0 },
  { g:"6CV3", m:"GOBIERNO DE TI|COMPUTER SECURITY", cupo:35, ins:35, disp:0 },
  { g:"6CV6", m:"ALGORITMOS BIOINSPIRADOS|GENETIC ALGORITHMS", cupo:1, ins:1, disp:0 },
  { g:"7CM2", m:"PROC. DE LENG|NATURAL LANGUAGE PROCESSING", cupo:36, ins:36, disp:0 },
  { g:"7CM2", m:"DESARROLLO DE APLICACIONES MOVILES NATIVAS", cupo:36, ins:36, disp:0 },
  { g:"7CM4", m:"ADMINISTRACION DE SERVICIOS EN RED", cupo:34, ins:34, disp:0 },
  { g:"7CM5", m:"ADMINISTRACION DE SERVICIOS EN RED", cupo:34, ins:34, disp:0 },
  { g:"7CV1", m:"TRABAJO TERMINAL I", cupo:36, ins:36, disp:0 },
  { g:"7CV2", m:"SISTEMAS DISTRIBUIDOS", cupo:36, ins:36, disp:0 },
  { g:"7CV2", m:"COMPUTACION GRAFICA|VIRTUAL AND AUGMENTED REALITY", cupo:36, ins:36, disp:0 },
  { g:"7CV2", m:"DESARROLLO DE APLICACIONES MOVILES NATIVAS", cupo:36, ins:36, disp:0 },
  { g:"7CV2", m:"ADMINISTRACION DE SERVICIOS EN RED", cupo:34, ins:34, disp:0 },
  { g:"7CV3", m:"TRABAJO TERMINAL I", cupo:36, ins:36, disp:0 },
  { g:"7CV4", m:"GOBIERNO DE TI|IT GOVERNANCE", cupo:36, ins:36, disp:0 },
  { g:"7CV5", m:"GES. DE EMP. DE ALTA TEC|ECONOMIC ENGINEERING", cupo:36, ins:36, disp:0 },
  { g:"7CV6", m:"PROC. DE LENG|NATURAL LANGUAGE PROCESSING", cupo:2, ins:2, disp:0 },
  { g:"7CV7", m:"TOPICOS SEL. DE COM|COMPUTING SELECTED TOPICS II", cupo:1, ins:1, disp:0 },
  { g:"8CM1", m:"GESTION EMPRESARIAL", cupo:36, ins:36, disp:0 },
  { g:"8CV1", m:"LIDERAZGO PERSONAL", cupo:36, ins:36, disp:0 },
  { g:"8CV3", m:"LIDERAZGO PERSONAL", cupo:34, ins:34, disp:0 },
  { g:"8CV3", m:"DESARROLLO DE HABILIDADES SOCIALES PARA LA ALTA DIRECCION", cupo:36, ins:36, disp:0 },
  { g:"1CM9", m:"CALCULO", cupo:36, ins:37, disp:-1 },
  { g:"1CV4", m:"FUNDAMENTOS DE PROGRAMACION", cupo:36, ins:37, disp:-1 },
  { g:"2CM1", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:36, ins:37, disp:-1 },
  { g:"2CM1", m:"ALGEBRA LINEAL", cupo:36, ins:37, disp:-1 },
  { g:"2CM4", m:"CALCULO APLICADO", cupo:36, ins:37, disp:-1 },
  { g:"2CM4", m:"MECANICA Y ELECTROMAGNETISMO", cupo:36, ins:37, disp:-1 },
  { g:"2CM6", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:36, ins:37, disp:-1 },
  { g:"2CM6", m:"CALCULO APLICADO", cupo:36, ins:37, disp:-1 },
  { g:"2CV4", m:"ALGEBRA LINEAL", cupo:36, ins:37, disp:-1 },
  { g:"3CM1", m:"FUNDAMENTOS DE DISEÑO DIGITAL", cupo:36, ins:37, disp:-1 },
  { g:"3CM1", m:"FINANZAS EMPRESARIALES", cupo:36, ins:37, disp:-1 },
  { g:"3CM3", m:"FUNDAMENTOS DE DISEÑO DIGITAL", cupo:36, ins:37, disp:-1 },
  { g:"3CM4", m:"PARADIGMAS DE PROGRAMACION", cupo:36, ins:37, disp:-1 },
  { g:"3CM4", m:"BASES DE DATOS", cupo:36, ins:37, disp:-1 },
  { g:"3CM5", m:"ANALISIS Y DISEÑO DE ALGORITMOS", cupo:36, ins:37, disp:-1 },
  { g:"3CV1", m:"BASES DE DATOS", cupo:36, ins:37, disp:-1 },
  { g:"4CM2", m:"MATEMATICAS AVANZADAS PARA LA INGENIERIA", cupo:36, ins:37, disp:-1 },
  { g:"4CM2", m:"SISTEMAS OPERATIVOS", cupo:34, ins:35, disp:-1 },
  { g:"4CM3", m:"TEORIA DE LA COMPUTACION", cupo:36, ins:37, disp:-1 },
  { g:"4CV1", m:"PROBABILIDAD Y ESTADISTICA", cupo:36, ins:37, disp:-1 },
  { g:"4CV1", m:"ELECTRONICA ANALOGICA", cupo:36, ins:37, disp:-1 },
  { g:"4CV2", m:"DISEÑO DE SISTEMAS DIGITALES", cupo:36, ins:37, disp:-1 },
  { g:"4CV2", m:"ELECTRONICA ANALOGICA", cupo:36, ins:37, disp:-1 },
  { g:"4CV4", m:"SISTEMAS OPERATIVOS", cupo:36, ins:37, disp:-1 },
  { g:"5CM1", m:"REDES DE COMPUTADORAS", cupo:36, ins:37, disp:-1 },
  { g:"5CM2", m:"COMPILADORES", cupo:36, ins:37, disp:-1 },
  { g:"5CM2", m:"PROCESAMIENTO DIGITAL DE SEÑALES", cupo:35, ins:36, disp:-1 },
  { g:"5CM2", m:"ANALISIS Y DISEÑO DE SISTEMAS", cupo:36, ins:37, disp:-1 },
  { g:"5CM2", m:"FORMULACION Y EVALUACION DE PROYECTOS INFORMATICOS", cupo:36, ins:37, disp:-1 },
  { g:"5CM3", m:"COMPILADORES", cupo:36, ins:37, disp:-1 },
  { g:"5CM3", m:"ARQUITECTURA DE COMPUTADORAS", cupo:34, ins:35, disp:-1 },
  { g:"5CM3", m:"FORMULACION Y EVALUACION DE PROYECTOS INFORMATICOS", cupo:36, ins:37, disp:-1 },
  { g:"5CM5", m:"INSTRUMENTACION Y CONTROL", cupo:36, ins:37, disp:-1 },
  { g:"5CM5", m:"FORMULACION Y EVALUACION DE PROYECTOS INFORMATICOS", cupo:36, ins:37, disp:-1 },
  { g:"5CM5", m:"REDES DE COMPUTADORAS", cupo:36, ins:37, disp:-1 },
  { g:"5CV1", m:"ANALISIS Y DISEÑO DE SISTEMAS", cupo:36, ins:37, disp:-1 },
  { g:"5CV2", m:"REDES DE COMPUTADORAS", cupo:36, ins:37, disp:-1 },
  { g:"5CV3", m:"ANALISIS Y DISEÑO DE SISTEMAS", cupo:36, ins:37, disp:-1 },
  { g:"5CV4", m:"PROCESAMIENTO DIGITAL DE SEÑALES", cupo:35, ins:36, disp:-1 },
  { g:"6CM1", m:"CRIPTOGRAFIA|INTRODUCTION TO CRYPTOGRAPHY", cupo:36, ins:37, disp:-1 },
  { g:"6CM1", m:"GES. DE EMP. DE ALTA TEC|HIGH TECHNOLOGY ENTERPRISE MANAGEMENT", cupo:36, ins:37, disp:-1 },
  { g:"6CM3", m:"METODOS CUANTITATIVOS PARA LA TOMA DE DECISIONES", cupo:36, ins:37, disp:-1 },
  { g:"6CM3", m:"INGENIERIA DE SOFTWARE", cupo:35, ins:36, disp:-1 },
  { g:"6CM6", m:"MINERIA DE DATOS|STATISTICAL TOOLS FOR DATA ANALYTICS", cupo:36, ins:37, disp:-1 },
  { g:"6CV2", m:"SISTEMAS EN CHIP", cupo:36, ins:37, disp:-1 },
  { g:"6CV2", m:"METODOS CUANTITATIVOS PARA LA TOMA DE DECISIONES", cupo:36, ins:37, disp:-1 },
  { g:"6CV5", m:"PROC. DE LENG. NAT|MACHINE LEARNING", cupo:36, ins:37, disp:-1 },
  { g:"1CM1", m:"MATEMATICAS DISCRETAS", cupo:36, ins:38, disp:-2 },
  { g:"1CM1", m:"ANALISIS VECTORIAL", cupo:36, ins:38, disp:-2 },
  { g:"1CM4", m:"ANALISIS VECTORIAL", cupo:36, ins:38, disp:-2 },
  { g:"2CM2", m:"INGENIERIA ETICA Y SOCIEDAD", cupo:36, ins:38, disp:-2 },
  { g:"2CM3", m:"ALGEBRA LINEAL", cupo:36, ins:38, disp:-2 },
  { g:"2CM3", m:"CALCULO APLICADO", cupo:36, ins:38, disp:-2 },
  { g:"2CM4", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:36, ins:38, disp:-2 },
  { g:"2CM4", m:"FUNDAMENTOS ECONOMICOS", cupo:36, ins:38, disp:-2 },
  { g:"2CM5", m:"ALGEBRA LINEAL", cupo:36, ins:38, disp:-2 },
  { g:"2CV4", m:"ALGORITMOS Y ESTRUCTURA DE DATOS", cupo:36, ins:38, disp:-2 },
  { g:"3CM2", m:"BASES DE DATOS", cupo:36, ins:38, disp:-2 },
  { g:"3CM3", m:"CIRCUITOS ELECTRICOS", cupo:36, ins:38, disp:-2 },
  { g:"3CM3", m:"BASES DE DATOS", cupo:36, ins:38, disp:-2 },
  { g:"4CM2", m:"PROBABILIDAD Y ESTADISTICA", cupo:36, ins:38, disp:-2 },
  { g:"4CM4", m:"PROBABILIDAD Y ESTADISTICA", cupo:36, ins:38, disp:-2 },
  { g:"4CM5", m:"TEORIA DE LA COMPUTACION", cupo:36, ins:38, disp:-2 },
  { g:"4CV3", m:"DISEÑO DE SISTEMAS DIGITALES", cupo:36, ins:38, disp:-2 },
  { g:"4CV3", m:"TECNOLOGIAS PARA DESARROLLO DE APLICACIONES WEB", cupo:36, ins:38, disp:-2 },
  { g:"4CV4", m:"PROBABILIDAD Y ESTADISTICA", cupo:36, ins:38, disp:-2 },
  { g:"5CM4", m:"COMPILADORES", cupo:35, ins:37, disp:-2 },
  { g:"5CM4", m:"PROCESAMIENTO DIGITAL DE SEÑALES", cupo:36, ins:38, disp:-2 },
  { g:"5CM4", m:"ANALISIS Y DISEÑO DE SISTEMAS", cupo:36, ins:38, disp:-2 },
  { g:"5CM5", m:"PROCESAMIENTO DIGITAL DE SEÑALES", cupo:35, ins:37, disp:-2 },
  { g:"5CV1", m:"PROCESAMIENTO DIGITAL DE SEÑALES", cupo:35, ins:37, disp:-2 },
  { g:"5CV1", m:"ARQUITECTURA DE COMPUTADORAS", cupo:35, ins:37, disp:-2 },
  { g:"5CV1", m:"REDES DE COMPUTADORAS", cupo:36, ins:38, disp:-2 },
  { g:"5CV3", m:"PROCESAMIENTO DIGITAL DE SEÑALES", cupo:36, ins:38, disp:-2 },
  { g:"5CV3", m:"INSTRUMENTACION Y CONTROL", cupo:34, ins:36, disp:-2 },
  { g:"6CM1", m:"SISTEMAS EN CHIP", cupo:36, ins:38, disp:-2 },
  { g:"6CM2", m:"INSTRUMENTAL VIRTUAL|VIRTUAL INSTRUMENTATION", cupo:36, ins:38, disp:-2 },
  { g:"6CM4", m:"METODOS CUANTITATIVOS PARA LA TOMA DE DECISIONES", cupo:36, ins:38, disp:-2 },
  { g:"6CV1", m:"SISTEMAS EN CHIP", cupo:36, ins:38, disp:-2 },
  { g:"6CV1", m:"METODOS CUANTITATIVOS PARA LA TOMA DE DECISIONES", cupo:36, ins:38, disp:-2 },
  { g:"6CV2", m:"INTELIGENCIA ARTIFICIAL", cupo:35, ins:37, disp:-2 },
  { g:"6CV2", m:"COMPUTACION GRAFICA|COMPUTER GRAPHICS", cupo:36, ins:38, disp:-2 },
  { g:"6CV4", m:"INTELIGENCIA ARTIFICIAL", cupo:36, ins:38, disp:-2 },
  { g:"6CV4", m:"ALGORITMOS BIOINSPIRADOS|GENETIC ALGORITHMS", cupo:36, ins:38, disp:-2 },
  { g:"7CM1", m:"SISTEMAS DISTRIBUIDOS", cupo:34, ins:36, disp:-2 },
  { g:"7CM5", m:"SISTEMAS DISTRIBUIDOS", cupo:36, ins:38, disp:-2 },
  { g:"7CV1", m:"CRIPTOGRAFIA|SELECTED TOPICS IN CRYPTOGRAPHY", cupo:34, ins:36, disp:-2 },
  { g:"7CV4", m:"DESARROLLO DE APLICACIONES MOVILES NATIVAS", cupo:36, ins:38, disp:-2 },
  { g:"8CM1", m:"TRABAJO TERMINAL II", cupo:36, ins:38, disp:-2 },
  { g:"8CV3", m:"GESTION EMPRESARIAL", cupo:34, ins:36, disp:-2 },
  { g:"3CM1", m:"ECUACIONES DIFERENCIALES", cupo:36, ins:39, disp:-3 },
  { g:"5CV4", m:"ARQUITECTURA DE COMPUTADORAS", cupo:36, ins:39, disp:-3 },
  { g:"6CM1", m:"APLICACIONES PARA COMUNICACIONES EN RED", cupo:36, ins:39, disp:-3 },
  { g:"6CM3", m:"BIG DATA|NON-RELATIONAL DATABASES", cupo:36, ins:39, disp:-3 },
  { g:"6CV1", m:"INTELIGENCIA ARTIFICIAL", cupo:36, ins:40, disp:-4 },
];
