// ========== FUENTES MANUALES POR MAESTRO (generado desde maestros_manual.csv) ==========
// nombre -> { link } . Editable: corrige maestros_manual.csv y regenera este .js.
// Se carga con <script> para que funcione tambien al abrir el HTML sin servidor (file://).
const MANUAL_LINKS = {
  "AGUILAR GARCIA RAFAEL": { link: "https://www.misprofesores.com/profesores/Rafael-Aguilar-Garcia_32564" },
  "AGUILAR SANCHEZ FERNANDO": { link: "https://www.misprofesores.com/profesores/Fernando-Aguilar-Sanchez_36942" },
  "AGUSTIN DOMINGUEZ VERONICA": { link: "https://www.misprofesores.com/profesores/Veronica-Agustin-Dominguez_81650" },
  "ALBORTANTE MORATO CECILIA": { link: "https://www.misprofesores.com/profesores/CECILIA-ALBORTANTE-MORATO_139095" },
  "ALCANTARA MENDEZ ALBERTO JESUS": { link: "https://www.misprofesores.com/profesores/Alberto-Jesus-Alcantara-Mendez_32201" },
  "ALCARAZ TORRES JUAN JESUS": { link: "https://www.misprofesores.com/profesores/Juan-Jesus-Alcaraz-Torres_54284" },
  "ALEMAN ARCE MIGUEL ANGEL": { link: "https://www.misprofesores.com/profesores/MIGUEL-ANGEL-ALEMAN-ARCE_161476" },
  "ALMAZAN FARFAN ROCIO": { link: "https://www.misprofesores.com/profesores/ROCIO-ALMAZAN-FARFAN_36702" },
  "ARCOS DIAZ ELSA LETICIA": { link: "https://www.misprofesores.com/profesores/Elsa-Leticia-Arcos-Diaz_166842" },
  "ARREDONDO SANCHEZ ANA LAURA": { link: "https://www.misprofesores.com/profesores/ANA-LAURA-ARREDONDO-SANCHEZ_187685" },
  "ARZATE GORDILLO JACQUELINE": { link: "https://www.misprofesores.com/profesores/Jaqueline-Arzate-Gordillo_26667" },
  "AVILA SANCHEZ CRISTHIAN ALEJANDRO": { link: "https://www.misprofesores.com/profesores/Cristhian-Alejandro-Avila-Sanches_108267" },
  "BARRALES LOPEZ ANA LUZ": { link: "https://www.misprofesores.com/profesores/Ana-Luz-Barrales-Lopez_182628" },
  "BARRON VERA JOSUE EMANUEL": { link: "https://www.misprofesores.com/profesores/josue-barron-vera_108138" },
  "BAUTISTA ROSALES SANDRA IVETTE": { link: "https://www.misprofesores.com/profesores/Sandra-Ivette-Bautista-Rosales_72205" },
  "BLANCO ALMAZAN IVAN EDUARDO": { link: "https://www.misprofesores.com/profesores/Ivan-Eduardo-Blanco-Almazan_134344?pag=4" },
  "BUITRON DAMASO ISRAEL": { link: "https://www.misprofesores.com/profesores/ISRAEL-BUITRON-DAMASO_59068" },
  "CABRERA CHAVEZ GLORIA LOURDES": { link: "https://www.misprofesores.com/profesores/Gloria-Lourdes-Cabrera-Chavez_75866" },
  "CALDERON SAMBARINO MARIA JULIA": { link: "https://www.misprofesores.com/profesores/Maria-Julia-Calderon-Sambarino_41226" },
  "CAMACHO VAZQUEZ VANESSA ALEJANDRA": { link: "https://www.misprofesores.com/profesores/VANESSA-ALEJANDRA-CAMACHO-VAZQUEZ_172919" },
  "CAÑEDO SUAREZ LETICIA": { link: "https://www.misprofesores.com/profesores/Leticia-Canedo-Suarez_37380" },
  "CARBALLO JIMENEZ JUAN MANUEL": { link: "https://www.misprofesores.com/profesores/Juan-Manuel-Carballo-Jimenez_18610" },
  "CARMONA GARCIA ENRIQUE ALFONSO": { link: "https://www.misprofesores.com/profesores/Enrique-Carmona_173014" },
  "CARRANZA CASTILLO OSCAR": { link: "https://www.misprofesores.com/profesores/Oscar-Carranza_49780" },
  "CARRETO ARELLANO CHADWICK": { link: "https://www.misprofesores.com/profesores/Chadwick-Carreto-Arellano_27575" },
  "CASTILLO CABRERA GELACIO": { link: "https://www.misprofesores.com/profesores/GELACIO-CASTILLO-CABRERA_40736" },
  "CASTILLO MARRUFO JUAN ANTONIO": { link: "https://www.misprofesores.com/profesores/Juan-Antonio-Castillo-Marrufo_46409" },
  "CASTILLO MARTÍNEZ MIGUEL ÁNGEL": { link: "https://www.misprofesores.com/profesores/Miguel-Angel-Castillo-Martinez_181507" },
  "CEBALLOS SEBASTIAN RICARDO": { link: "https://www.misprofesores.com/profesores/Ricardo-Ceballos-Sebastian_37147" },
  "CENTENO ARRAZOLA MARIA SOLEDAD": { link: "https://www.misprofesores.com/profesores/Maria-Soledad-Centeno-Arrazola_173169" },
  "CERVANTES DE ANDA ISMAEL": { link: "https://www.misprofesores.com/profesores/Ismael-Cervantes-de-Anda_27238" },
  "CERVANTES ESPINOSA LUIS MOCTEZUMA": { link: "https://www.misprofesores.com/profesores/Luis-Moctezuma-Cervantes-Espinoza_40667" },
  "CHAVARRIA BAEZ LORENA": { link: "https://www.misprofesores.com/profesores/Lorena-Chavarria-Baez_25549" },
  "CHAVEZ LIMA EDUARDO": { link: "https://www.misprofesores.com/profesores/Eduardo-Chavez-Lima_18617" },
  "CIFUENTES ALVAREZ ALEJANDRO SIGFRIDO": { link: "https://www.misprofesores.com/profesores/Aljeandro-Sigfrido-Cifuentes-Alvarez_41228" },
  "CORDERO LOPEZ MARTHA ROSA": { link: "https://www.misprofesores.com/profesores/MARTHA-ROSA-CORDERO-LOPEZ_41541" },
  "CORONILLA CONTRERAS UKRANIO": { link: "https://www.misprofesores.com/profesores/UKRANIO-CORONILLA_26980" },
  "CORREA COYAC DAVID": { link: "https://www.misprofesores.com/profesores/David-Correa-Coyac_177040" },
  "CORTÉS DÁVALOS ANDRÉS": { link: "https://www.misprofesores.com/profesores/Andres-Cortes-Davalos_182249" },
  "CORTES GALICIA JORGE": { link: "https://www.misprofesores.com/profesores/Jorge-Cortes-Galicia_40470" },
  "CORTEZ DUARTE NIDIA ASUNCIÓN": { link: "https://www.misprofesores.com/profesores/Nidia-Asuncion-Cortes-Duarte_35872" },
  "CRUZ CARLIN EFREN": { link: "https://www.misprofesores.com/profesores/Efren-Cruz-Carlin_166851" },
  "CRUZ GARCIA DANIEL": { link: "https://www.misprofesores.com/profesores/daniel-cruz-garcia_41229" },
  "CRUZ MEZA MARIA ELENA": { link: "https://www.misprofesores.com/profesores/Maria-Elena-Cruz-Meza_41789" },
  "CRUZ ROJAS JORGE ALBERTO": { link: "https://www.misprofesores.com/profesores/Jorger-Alberto-Cruz-Rojas_148153" },
  "DAVALOS LOPEZ JOSE CARLOS": { link: "https://www.misprofesores.com/profesores/Juan-Jose-Davalos-Lopez_100680" },
  "DE LUNA CABALLERO ROBERTO": { link: "https://www.misprofesores.com/profesores/Roberto-De-Luna-Caballero_29034" },
  "DIAZ HUERTA CLAUDIA CELIA": { link: "https://www.misprofesores.com/profesores/claudia-celia-DIAZ-HUERTA_51280" },
  "DIAZ SANCHEZ HUGO": { link: "https://www.misprofesores.com/profesores/Hugo-Diaz-Sanchez_181488" },
  "DIAZ SANTIAGO RICARDO FELIPE": { link: "https://www.misprofesores.com/profesores/Ricardo-Felipe-Diaz-de-Santiago_22498" },
  "DIAZ SANTIAGO SANDRA": { link: "https://www.misprofesores.com/profesores/Sandra-Diaz_72290" },
  "DIAZ TOALA IVAN": { link: "https://www.misprofesores.com/profesores/IVAN-DIAZ-TOALA_40755" },
  "DOMINGUEZ HERNANDEZ SAMUEL": { link: "https://www.misprofesores.com/profesores/Samuel-Dominguez-Hernandez_179045" },
  "DORANTES CORDERO MARTHA MARGARITA": { link: "https://www.misprofesores.com/profesores/MARTHA-MARGARITA-DORANTES-CORDERO_182002" },
  "DORANTES VILLA CLAUDIA JISELA": { link: "https://www.misprofesores.com/profesores/Claudia-Jisela-Dorantes-Villa_36840" },
  "DURÀN CAMARILLO EDMUNDO RENÈ": { link: "https://www.misprofesores.com/profesores/Edmundo-Rene-Duran-Camarillo_38205" },
  "ENRIQUEZ ZARATE Dr. JOSE ASUNCION": { link: "https://www.misprofesores.com/profesores/Jose-Asuncion-Enriquez-Zarate_46663" },
  "ESCAMILLA MIRANDA PATRICIA": { link: "https://www.misprofesores.com/profesores/Patricia-Escamilla-Miranda_120943" },
  "ESQUIVEL CENTENO JOSE ARMANDO": { link: "https://www.misprofesores.com/profesores/Armando-Esquivel-Centeno_18613" },
  "FERNANDEZ VAZQUEZ ALFONSO": { link: "https://www.misprofesores.com/profesores/ALFONSO-FERNANDEZ-VAZQUEZ_82880" },
  "FLORES DELGADO RAQUEL": { link: "https://www.misprofesores.com/profesores/Raquel-FLORES-DELGADO_75786" },
  "FLORES FUENTES NARIA ADRIANA": { link: "https://www.misprofesores.com/profesores/NARIA-ADRIANA-FLORES-FUENTES_38310" },
  "FLORES MENDOZA YAXKIN": { link: "https://www.misprofesores.com/profesores/Yaxkin-Flores-Mendoza_36537" },
  "FLORES MERAZ YESICA SONIA": { link: "https://www.misprofesores.com/profesores/YESICA-SONIA-FLORES-MERAZ_161606" },
  "FRANCO MARTINEZ EDGARDO ADRIAN": { link: "https://www.misprofesores.com/profesores/Edgardo-Adrian-Franco-Martinez_25963" },
  "GALEANA CHAVEZ M. en A.P. MARIA DEL ROSARIO": { link: "https://www.misprofesores.com/profesores/Maria-del-Rosario-Galenana-Chavez_148068" },
  "GALICIA MEJIA RUBEN": { link: "https://www.misprofesores.com/profesores/Ruben-Galicia-Mejia_46751" },
  "GALIÑANES RODRIGUEZ MARIA GABRIELA": { link: "https://www.misprofesores.com/profesores/Maria-Gabriela-Galinanes-Rodriguez_45929" },
  "GARCIA FLORIANO ANDRES": { link: "https://www.misprofesores.com/profesores/Andres-Garcia-Floriano_172614" },
  "GARCIA SALES JUAN VICENTE": { link: "https://www.misprofesores.com/profesores/Juan-Vicente-Garcia_34924" },
  "GASPAR MEDINA FABIAN": { link: "https://www.misprofesores.com/profesores/Fabian-Gaspar_114932" },
  "GOMEZ MAYORGA MARGARITA ELIZABETH": { link: "https://www.misprofesores.com/profesores/Margarita-Elizabeth-Gomez-Mayorga_35949" },
  "GOMEZ TRESS MARIANA": { link: "https://www.misprofesores.com/profesores/Mariana-Gomez-Tress_161428" },
  "GONZALEZ ALBARRAN GISELA": { link: "https://www.misprofesores.com/profesores/GISELA-GONZALEZ-ALBARRAN_38379" },
  "GONZALEZ CASTILLO JESUS ROBERTO": { link: "https://www.misprofesores.com/profesores/Jesus-Roberto-Gonzalez-Castillo_166635" },
  "GONZALEZ CISNEROS ALEJANDRO": { link: "https://www.misprofesores.com/profesores/Alejandro-Gonzalez-Cisneros_47846" },
  "GONZALEZ RAMIREZ MARKO ALFONSO": { link: "https://www.misprofesores.com/profesores/MARKO-ALFONSO-GONZALEZ-RAMIREZ_127605" },
  "GUTIERREZ MEJIA DARWIN": { link: "https://www.misprofesores.com/profesores/Darwin-Gutierrez-Mejia_32199" },
  "GUZMAN AGUILAR FLORENCIO": { link: "https://www.misprofesores.com/profesores/FLORENCIO-GUZMAN-AGUILAR_35905" },
  "GUZMAN FLORES JESSIE PAULINA": { link: "https://www.misprofesores.com/profesores/JESSIE-PAULINA-GUZMAN-FLORES_59069" },
  "HENESTROSA CARRASCO LETICIA": { link: "https://www.misprofesores.com/profesores/Leticia-Henestrosa-Carrasco_64190" },
  "HERNANDEZ AGUILAR JOSE LUIS": { link: "https://www.misprofesores.com/profesores/JOSE-LUIS-HERNANDEZ-AGUILAR_40740" },
  "HERNANDEZ OLVERA LUIS ENRIQUE": { link: "https://www.misprofesores.com/profesores/Luis-Enrique-Hernandez-Olvera_64460" },
  "HERNANDEZ SECUNDINO JOSE CELESTINO ELIAS": { link: "https://www.misprofesores.com/profesores/Jose-Celestino-Elias-Hernandez-Secundino_108386" },
  "HERNANDEZ VASQUEZ CESAR": { link: "https://www.misprofesores.com/profesores/CESAR-HERNANDEZ-VASQUEZ_133402" },
  "HERRERA YAÑEZ CRISPIN": { link: "https://www.misprofesores.com/profesores/CRISPIN-HERRERA-YANEZ_52816" },
  "HURTADO AVILÉS GABRIEL": { link: "https://www.misprofesores.com/profesores/Gabriel-Hurtado-Aviles_181032" },
  "JIMENEZ BENITEZ JOSE ALFREDO": { link: "https://www.misprofesores.com/profesores/Jose-Alfredo-Jimenez-Benitez_27484" },
  "JIMENEZ GALAN YASMIN IVETTE": { link: "https://www.misprofesores.com/profesores/Yasmin-Ivette-Jimenez-Galan_22560" },
  "JIMENEZ RUIZ RENE BALTAZAR": { link: "https://www.misprofesores.com/profesores/Rene-Baltazar-Jimenez-Ruiz_80611" },
  "JUAREZ LEON CARLOS": { link: "https://www.misprofesores.com/profesores/Carlos-Juarez-Leon_30233" },
  "JUAREZ MARTINEZ GENARO": { link: "https://www.misprofesores.com/profesores/Genaro-Juarez-Martinez_51074" },
  "JUÁREZ MÉNDEZ ANA BELEM": { link: "https://www.misprofesores.com/profesores/Ana-Belem-Juarez-Mendez_112059" },
  "JUAREZ RAMIREZ JAZMIN ADRIANA": { link: "https://www.misprofesores.com/profesores/Jazmin-Adriana-Juarez-Ramirez_36277" },
  "JURADO JIMENEZ ROBERTO": { link: "https://www.misprofesores.com/profesores/ROBERTO-JURADO-JIMENEZ_25341" },
  "LAZCANO XOXOTLA LAURA": { link: "https://www.misprofesores.com/profesores/Laura-Lazcano-Xoxotla_60404" },
  "LEAL PACHECO CHRISTIAN RENE": { link: "https://www.misprofesores.com/profesores/Cristian-Pacheco_172939" },
  "LEON HERNANDEZ MIGUEL ABEL": { link: "https://www.misprofesores.com/profesores/Miguel-Abel-Leon-Hernandez_36411" },
  "LERMA MAGAÑA CARLOS": { link: "https://www.misprofesores.com/profesores/Carlos-Lerma-Magana_182102" },
  "LEVARIO MEDINA SERGIO": { link: "https://www.misprofesores.com/profesores/Sergio-Levario-Medina_154603" },
  "LINARES VALLEJO ERICK EUGENIO": { link: "https://www.misprofesores.com/profesores/Erick-Eugenio-Linares-Vallejo_35112" },
  "LOPEZ CARRERA BENJAMIN": { link: "https://www.misprofesores.com/profesores/Benjamin-Lopez-Carrera_41460" },
  "LOPEZ LEYVA LUIS OCTAVIO": { link: "https://www.misprofesores.com/profesores/lUIS-OCTAVIO-LOPEZ-LEIVA_37434" },
  "LOPEZ ROJAS ARIEL": { link: "https://www.misprofesores.com/profesores/ariel-lopez-rojas_23217" },
  "LOPEZ SANCHEZ JOSE MANUEL": { link: "https://www.misprofesores.com/profesores/Jose-Manuel-Lopez-Sanchez_161740" },
  "LOYOLA ESPINOSA ARACELI": { link: "https://www.misprofesores.com/profesores/Araceli-Loyola-Espinoza_134228" },
  "LUCIO PEÑA PERLA CECILIA": { link: "https://www.misprofesores.com/profesores/Perla-Cecilia-Lucio-Pena_178581" },
  "LUNA BENOSO BENJAMIN": { link: "https://www.misprofesores.com/profesores/Benjamin-Luna-Benoso_21841" },
  "MALDONADO CASTILLO IDALIA": { link: "https://www.misprofesores.com/profesores/Idalia-Maldonado-Castillo_36341" },
  "MALDONADO MUÑOZ MIGUEL ANGEL": { link: "https://www.misprofesores.com/profesores/Miguel-Angel-Maldonado-Munoz_28269" },
  "MANZANILLA GRANADOS HECTOR MANUEL": { link: "https://www.misprofesores.com/profesores/Hector-Manuel-Manzanilla-Granados_36232" },
  "MARQUEZ ARREGUIN GUILLERMO": { link: "https://www.misprofesores.com/profesores/Guillermo-Marquez-Arreguin_51117" },
  "MARTINEZ ACOSTA LILIAN": { link: "https://www.misprofesores.com/profesores/Lilian-Martinez-Acosta_30438" },
  "MARTINEZ DIAZ JUAN CARLOS": { link: "https://www.misprofesores.com/profesores/Juan-Carlos-Martinez-Diaz_18615" },
  "MARTÍNEZ GARCÍA CÉSAR RÓMAN": { link: "https://www.misprofesores.com/profesores/Cesar-Roman-Martinez-Garcia_36418" },
  "MARTINEZ GUERRERO JOSE ALFREDO": { link: "https://www.misprofesores.com/profesores/Jose-Alfredo-Martinez-Guerrero_37501" },
  "MARTINEZ NUÑO JESUS ALFREDO": { link: "https://www.misprofesores.com/profesores/JESUS-ALFREDO-MARTINEZ-NUNO_30730" },
  "MARTINEZ PERALES JOSE CRUZ": { link: "https://www.misprofesores.com/profesores/Jose-Cruz-Martinez-Perales_46506" },
  "MARTINEZ ROSALES RICARDO": { link: "https://www.misprofesores.com/profesores/Ricardo-Martines-Rosales_69051" },
  "MEDINA MEJIA VIRGINIA": { link: "https://www.misprofesores.com/profesores/Vijinia-Mejia-Medina_24794" },
  "MELARA ABARCA REYNA ELIA": { link: "https://www.misprofesores.com/profesores/Reyna-Elia-Melara-Abarca_46396" },
  "MENDOZA MACIAS ELBA": { link: "https://www.misprofesores.com/profesores/ELBA-MENDOZA-MACIAS_25993" },
  "MIGUEL PILAR ZELIN": { link: "https://www.misprofesores.com/profesores/Zelin-Miguel-Pilar_24528" },
  "MONTIEL SANCHEZ ANGEL SALVADOR": { link: "https://www.misprofesores.com/profesores/ANGEL-SALVADOR-MONTIEL-SANCHEZ_30899" },
  "MORALES CRUZ JUAN CARLOS": { link: "https://www.misprofesores.com/profesores/Juan-Carlos-Morales-Cruz_27305" },
  "MORALES GONZALEZ ANGEL": { link: "https://www.misprofesores.com/profesores/Angel-Morales_27860" },
  "MORALES GUITRON SANDRA LUZ": { link: "https://www.misprofesores.com/profesores/SANDRA-LUZ-MORALES-GUITRON_36708" },
  "MORALES RODRIGUEZ URSULA SAMANTHA": { link: "https://www.misprofesores.com/profesores/URSULA-SAMANTHA-MORALES-RODRIGUEZ_154604" },
  "MORENO CERVANTES AXEL ERNESTO": { link: "https://www.misprofesores.com/profesores/Axel-Ernesto-Moreno-Cervantes_40753" },
  "MOSCOSO MALAGON YOSAFAT": { link: "https://www.misprofesores.com/profesores/YOSAFAT-MOSCOSO-MALAGON_32413" },
  "MUJICA ASCENCIO CESAR": { link: "https://www.misprofesores.com/profesores/Cesar-Mujica-Ascencio_32134" },
  "NÚÑEZ PRADO CÉSAR JESÚS": { link: "https://www.misprofesores.com/profesores/CESAR-JESUS-NUNEZ-PRADO_173659" },
  "NAVA LARA JOEL": { link: "https://www.misprofesores.com/profesores/Joel-Nava-Lara_90290" },
  "OCAMPO BOTELLO FABIOLA": { link: "https://www.misprofesores.com/profesores/FABIOLA-OCAMPO-BOTELLO_36696" },
  "OJEDA SANTILLAN RODRIGO": { link: "https://www.misprofesores.com/profesores/Rodrigo-Ojeda-Santillan_172613" },
  "OLALDE MOGOLLAN NORMA": { link: "https://www.misprofesores.com/profesores/Norma-Olalde-Mogollan_166503" },
  "ORTEGA GONZALEZ RUBEN": { link: "https://www.misprofesores.com/profesores/Ruben-Ortega-Gonzalez_51229" },
  "ORTIGOZA CAMPOS M. en C. ANDRES": { link: "https://www.misprofesores.com/profesores/Andres-Ortigoza-Campos_41860" },
  "ORTIZ CASTILLO MARCO ANTONIO": { link: "https://www.misprofesores.com/profesores/Marco-Antonio-Ortiz-Castillo_186347" },
  "ORTIZ RAMIREZ JOSE ANTONIO": { link: "https://www.misprofesores.com/profesores/JOSE-ANTONIO-ORTIZ-RAMIREZ_40751" },
  "ORTUÑO ARAUJO JESUS": { link: "https://www.misprofesores.com/profesores/Jesus-Ortuno-Araujo_38716" },
  "PACHUCA HERRERA YANIRA": { link: "https://www.misprofesores.com/profesores/Yanira-Pachuca-Herrera_161429" },
  "PALACIOS SOLANO ROCIO": { link: "https://www.misprofesores.com/profesores/Rocio-Solano-Palacios_95392" },
  "PALMA OROZCO ROSAURA": { link: "https://www.misprofesores.com/profesores/Rosaura-Palma-Orozco_46507" },
  "PAREDES CADENA MYRIAM NOEMI": { link: "https://www.misprofesores.com/profesores/Myriam-Noemi-Paredes-Cadena_113407" },
  "PASTRANA FERNANDEZ CARLOS JESUS": { link: "https://www.misprofesores.com/profesores/Carlos-Jesus-Pastrana-Fernandez_72344?pag=2" },
  "PEREDO VALDERRAMA RUBEN": { link: "https://www.misprofesores.com/profesores/Ruben-PEREDO-VALDERRAMA_41594" },
  "PEREZ DE LOS SANTOS MONDRAGON TANIBET": { link: "https://www.misprofesores.com/profesores/Mondragon-Tanibet-Perez-de-los-santos_41488" },
  "PEREZ PEREZ JOSE JUAN": { link: "https://www.misprofesores.com/profesores/Jose-Juan-Perez-Perez_182852" },
  "PINEDA GUERRERO CARLOS": { link: "https://www.misprofesores.com/profesores/Carlos-Pineda-Guerrero_120837" },
  "PUEBLA LOMAS JAIME HUGO": { link: "https://www.misprofesores.com/profesores/jaime-hugo-puebla-lomas_50910" },
  "RAMIREZ ROMERO TONAHTIU ARTURO": { link: "https://www.misprofesores.com/profesores/TONAHTIU-ARTURO-RAMIREZ-ROMERO_69232" },
  "RESENDIZ MUÑOZ ROCIO": { link: "https://www.misprofesores.com/profesores/Rocio-Resendiz-Munoz_31944" },
  "REYES BERMEJO TLATOANI DE JESUS": { link: "https://www.misprofesores.com/profesores/TLATOANI-DE-JESUS-REYES-BERMEJO_31985" },
  "REYES VERA ABDIEL": { link: "https://www.misprofesores.com/profesores/Abdiel-Reyes-Vera_181487" },
  "RIVERA DE LA ROSA MONICA": { link: "https://www.misprofesores.com/profesores/Monica-Rivera-de-la-Rosa_34427" },
  "RODRIGUEZ CASTILLO MIGUEL ANGEL": { link: "https://www.misprofesores.com/profesores/Miguel-Angel-Rodriguez-Castillo_124446" },
  "RODRIGUEZ FLORES EDUARDO": { link: "https://www.misprofesores.com/profesores/EDUARDO-RODRIGUEZ-FLORES_40734" },
  "RODRIGUEZ JORDAN GABRIEL DE JESUS": { link: "https://www.misprofesores.com/profesores/Gabriel-de-Jesus-Rodriguez-Jordan_165125" },
  "RODRIGUEZ ORDAZ MARISOL": { link: "https://www.misprofesores.com/profesores/Marisol-Rodriguez-Ordaz_107759" },
  "RODRIGUEZ SARABIA TANIA": { link: "https://www.misprofesores.com/profesores/TANIA-RODRIGUEZ-SARABIA_100422" },
  "RODRIGUEZ VILLARREAL JOSE GREGORIO": { link: "https://www.misprofesores.com/profesores/Jose-Gregorio-Rodriguez_173007" },
  "ROJAS MEXICANO ISMAEL": { link: "https://www.misprofesores.com/profesores/Ismael-Rojas-Mexicano_27473" },
  "ROMÁN GODÍNEZ RODRIGO FRANCISCO": { link: "https://www.misprofesores.com/profesores/Rodrigo-Francisco-Roman-Godinez_181435" },
  "ROMERO HERRERA RODOLFO": { link: "https://www.misprofesores.com/profesores/rodolfo-romero-herrera_56142" },
  "ROSAS CARRILLO ARY SHARED": { link: "https://www.misprofesores.com/profesores/Ary-Shared-Rosas-Castillo_166948" },
  "ROSAS TRIGUEROS JORGE LUIS": { link: "https://www.misprofesores.com/profesores/Jorge-Luis-Rosas-Mendoza_43076" },
  "RUIZ LEDESMA ELENA FABIOLA": { link: "https://www.misprofesores.com/profesores/Elena-Fabiola-Ruiz-Ledesma_18618" },
  "SALAZAR RAMIREZ MANUEL": { link: "https://www.misprofesores.com/profesores/Manuel-Salazar-Ramirez_46659" },
  "SALDÍVAR ALMOREJO MARÍA MAGDALENA": { link: "https://www.misprofesores.com/profesores/Maria-Magdalena-Saldivar-Almorejo_177039" },
  "SALINAS CALLEJAS MARÍA DE LOURDES": { link: "https://www.misprofesores.com/profesores/Maria-de-lourdes-callejas-salinas_182584" },
  "SALINAS HERNANDEZ ENCARNACION": { link: "https://www.misprofesores.com/profesores/encarnacion-salinas-hernandez_43174" },
  "SANCHEZ ARROYO JOSE EMILIO": { link: "https://www.misprofesores.com/profesores/Jose-Emilio-Sanchez-Arroyo_134871" },
  "SANCHEZ BRITO MIGUEL": { link: "https://www.misprofesores.com/profesores/Miguel-Sanchez-Brito_154593" },
  "SANCHEZ CRUZ VIRGINIA": { link: "https://www.misprofesores.com/profesores/VIRGINIA-SANCHEZ-CRUZ_32050" },
  "SANCHEZ GARCIA LUZ MARIA": { link: "https://www.misprofesores.com/profesores/Luz-Maria-Sanchez-Garcia_41700" },
  "SANCHEZ JUAREZ JOSE": { link: "https://www.misprofesores.com/profesores/Jose-Sanchez-Juarez_105323" },
  "SANCHEZ MORENO ADRIANA DE LA P": { link: "https://www.misprofesores.com/profesores/Adriana-Sanchez-Moreno_38715" },
  "SANCHEZ PALACIOS MARIA SUSANA": { link: "https://www.misprofesores.com/profesores/Maria-Susana-Sanchez-Palacios_42022" },
  "SANCHEZ QUINTANILLA GILBERTO": { link: "https://www.misprofesores.com/profesores/Gilberto-Sanchez-Quintanilla_36963" },
  "SANCHEZ VARGAS PERLA REBECA": { link: "https://www.misprofesores.com/profesores/Sanchez-Vargas-Perla-Rebeca_92539" },
  "SANCHEZ VELEZ RICARDO": { link: "https://www.misprofesores.com/profesores/Ricardo-Sanchez-Velez_166082" },
  "SANTIAGO VALENTIN ERIC": { link: "https://www.misprofesores.com/profesores/Eric-Santiago-Valentin_166233" },
  "SANTILLAN LUNA RAUL": { link: "https://www.misprofesores.com/profesores/Raul-Santillan-Luna_56290" },
  "SERRANO ROMERO CLAUDIA WENDY": { link: "https://misprofesores.com/profesores/Claudia-Wendy-Serrano-Romero_189554" },
  "SILVA GARCIA VICTOR MANUEL": { link: "https://www.misprofesores.com/profesores/Victor-Manuel-Silva-Garcia_50624" },
  "SILVA MARTINEZ JORGE JAVIER": { link: "https://www.misprofesores.com/profesores/Jorge-Javier-Silva-Martinez_32563" },
  "SILVA SANCHEZ CARLOS": { link: "https://www.misprofesores.com/profesores/Carlos-Silva_28421" },
  "SOLORZA GUZMAN MISAEL": { link: "https://www.misprofesores.com/profesores/Misael-Solorza-Guzman_32991" },
  "SOSA ADAN FANNY": { link: "https://misprofesores.com/profesores/Fanny-Adan-Sosa_135983" },
  "SOTO RAMOS MANUEL ALEJANDRO": { link: "https://www.misprofesores.com/profesores/MANUEL-ALEJANDRO-SOTO-RAMOS_28304" },
  "TECLA PARRA ROBERTO": { link: "https://www.misprofesores.com/profesores/Roberto-Tecla-Parra_32018" },
  "TELLEZ BARRERA JUAN CARLOS": { link: "https://www.misprofesores.com/profesores/Juan-Carlos-Tellez-Barrera_113020" },
  "TELLEZ REYES MA. DEL SOCORRO": { link: "https://www.misprofesores.com/profesores/Maria-del-Socorro-Tellez-Reyes_108013" },
  "TENORIO MARRON MARCO ANTONIO": { link: "https://www.misprofesores.com/profesores/Marco-Antonio-Marron-Tenorio_154635" },
  "TESTA NAVA ALEXIS": { link: "https://www.misprofesores.com/profesores/Alexis-Testa-Navas_113459" },
  "TIRADO LULE JUDITH MARGARITA": { link: "https://www.misprofesores.com/profesores/Judith-Margarita-Tirado-Lule_26714" },
  "TORRES GONZALEZ ENRIQUE": { link: "https://www.misprofesores.com/profesores/ENRIQUE-TORRES-GONZALEZ_36707" },
  "VAZQUEZ ARREGUIN ROBERTO": { link: "https://www.misprofesores.com/profesores/Roberto-Vazquez-Arreguin_36420" },
  "VAZQUEZ ORTIZ MIJAIL": { link: "https://www.misprofesores.com/profesores/Mijail-Vazquez-Ortiz_80630" },
  "VELEZ SALDAÑA ULISES": { link: "https://www.misprofesores.com/profesores/Ulises-Velez-Saldana_31636" },
  "VILLEGAS NAVARRETE SONIA": { link: "https://www.misprofesores.com/profesores/Sonia-Villegas-Navarrete_54380" },
  "VIVEROS VELA KARINA": { link: "https://www.misprofesores.com/profesores/Karina-Viveros-Vela_18612" },
  "WINFIELD REYES ANA MARIA": { link: "https://www.misprofesores.com/profesores/ANA-MARIA-WINFIELD-REYES_36765" },
  "ZARATE CARDENAS ALEJANDRO": { link: "https://www.misprofesores.com/profesores/Alejandro-Zarate-Cardenas_126790" },
};
