// ========== CALIFICACIONES POR MAESTRO (generado desde AESTR_CORREGIDO_3.csv + AESTR_VESPERTINO_plantilla.csv) ==========
// calidad 0-10 · recomiendan 0-100 (%) · dificultad 0-6 · '' = sin dato
// Correcciones: BARRALES recomiendan 1.4->14, TELLEZ BARRERA columnas invertidas (rec/dif)
const TEACHER_METRICS = {
  "DORANTES VILLA CLAUDIA JISELA": { calidad: 6.7, recomiendan: 57, dificultad: 3.1 },
  "SANCHEZ VARGAS PERLA REBECA": { calidad: 7.7, recomiendan: 84, dificultad: 3.3 },
  "JUAREZ RAMIREZ JAZMIN ADRIANA": { calidad: 8.9, recomiendan: 86, dificultad: 2.9 },
  "LOPEZ SANCHEZ JOSE MANUEL": { calidad: 9.0, recomiendan: 93, dificultad: 4.1 },
  "FLORES FUENTES NARIA ADRIANA": { calidad: 9.2, recomiendan: 94, dificultad: 4.2 },
  "LEAL PACHECO CHRISTIAN RENE": { calidad: 8.7, recomiendan: 100, dificultad: 2.7 },
  "MARTÍNEZ GARCÍA CÉSAR RÓMAN": { calidad: 9.0, recomiendan: 93, dificultad: 1.1 },
  "SILVA GARCIA VICTOR MANUEL": { calidad: 8.5, recomiendan: 89, dificultad: 1.7 },
  "RESENDIZ MUÑOZ ROCIO": { calidad: 5.8, recomiendan: 43, dificultad: 5.1 },
  "PAREDES CADENA MYRIAM NOEMI": { calidad: 6.8, recomiendan: 46, dificultad: 1.2 },
  "FRANCO MARTINEZ EDGARDO ADRIAN": { calidad: 8.6, recomiendan: 88, dificultad: 3.6 },
  "DAVALOS LOPEZ JOSE CARLOS": { calidad: 8.3, recomiendan: 86, dificultad: 3 },
  "HERRERA YAÑEZ CRISPIN": { calidad: 5.9, recomiendan: 45, dificultad: 4.1 },
  "DIAZ SANCHEZ HUGO": { calidad: 7.0, recomiendan: 60, dificultad: 3.6 },
  "SANCHEZ PALACIOS MARIA SUSANA": { calidad: 5.5, recomiendan: 43, dificultad: 3.7 },
  "PACHUCA HERRERA YANIRA": { calidad: 8.1, recomiendan: 83, dificultad: 1.6 },
  "REYES BERMEJO TLATOANI DE JESUS": { calidad: 6.4, recomiendan: 48, dificultad: 5.2 },
  "GUZMAN AGUILAR FLORENCIO": { calidad: 7.9, recomiendan: 85, dificultad: 1.6 },
  "MIGUEL PILAR ZELIN": { calidad: 6.3, recomiendan: 64, dificultad: 3.3 },
  "SANCHEZ VELEZ RICARDO": { calidad: 4.9, recomiendan: 27, dificultad: 5.1 },
  "LUCIO PEÑA PERLA CECILIA": { calidad: 8.4, recomiendan: 80, dificultad: 3.6 },
  "RODRIGUEZ VILLARREAL JOSE GREGORIO": { calidad: 7.8, recomiendan: 75, dificultad: 4 },
  "SANCHEZ MORENO ADRIANA DE LA P": { calidad: 9.4, recomiendan: 94, dificultad: 0.9 },
  "SERRANO ROMERO CLAUDIA WENDY": { calidad: 6.7, recomiendan: 67, dificultad: 2.7 },
  "CENTENO ARRAZOLA MARIA SOLEDAD": { calidad: 7.9, recomiendan: 80, dificultad: 0.4 },
  "TELLEZ REYES MA. DEL SOCORRO": { calidad: 9.6, recomiendan: 100, dificultad: 0.2 },
  "TECLA PARRA ROBERTO": { calidad: 7.2, recomiendan: 79, dificultad: 1.5 },
  "DE LUNA CABALLERO ROBERTO": { calidad: 3.1, recomiendan: 7, dificultad: 4.2 },
  "ALBORTANTE MORATO CECILIA": { calidad: 8.9, recomiendan: 92, dificultad: 1.4 },
  "FLORES MENDOZA YAXKIN": { calidad: 5.7, recomiendan: 44, dificultad: 3.2 },
  "MORALES GONZALEZ ANGEL": { calidad: 6.7, recomiendan: 57, dificultad: 4.6 },
  "VAZQUEZ ARREGUIN ROBERTO": { calidad: 6.9, recomiendan: 68, dificultad: 2.1 },
  "CAÑEDO SUAREZ LETICIA": { calidad: 8.0, recomiendan: 72, dificultad: 4.6 },
  "VIVEROS VELA KARINA": { calidad: 8.3, recomiendan: 86, dificultad: 3.6 },
  "ARCOS DIAZ ELSA LETICIA": { calidad: 4.9, recomiendan: 31, dificultad: 5.8 },
  "AVILA SANCHEZ CRISTHIAN ALEJANDRO": { calidad: 7.0, recomiendan: 66, dificultad: 3.9 },
  "RUIZ LEDESMA ELENA FABIOLA": { calidad: 7.4, recomiendan: 69, dificultad: 3.1 },
  "SALINAS HERNANDEZ ENCARNACION": { calidad: 6.6, recomiendan: 54, dificultad: 5.7 },
  "CORREA COYAC DAVID": { calidad: 7.9, recomiendan: 70, dificultad: 2 },
  "HERNANDEZ VASQUEZ CESAR": { calidad: 8.2, recomiendan: 80, dificultad: 4.1 },
  "CEBALLOS SEBASTIAN RICARDO": { calidad: 6.4, recomiendan: 62, dificultad: 3.7 },
  "SANCHEZ ARROYO JOSE EMILIO": { calidad: 3.6, recomiendan: 20, dificultad: 3.7 },
  "MARTINEZ ACOSTA LILIAN": { calidad: 7.2, recomiendan: 70, dificultad: 4.3 },
  "CASTILLO MARRUFO JUAN ANTONIO": { calidad: 8.2, recomiendan: 86, dificultad: 3.9 },
  "GALIÑANES RODRIGUEZ MARIA GABRIELA": { calidad: 6.9, recomiendan: 60, dificultad: 3 },
  "SANCHEZ CRUZ VIRGINIA": { calidad: 6.1, recomiendan: 51, dificultad: 3.3 },
  "TORRES GONZALEZ ENRIQUE": { calidad: 7.1, recomiendan: 64, dificultad: 0.9 },
  "DIAZ SANTIAGO RICARDO FELIPE": { calidad: 7.2, recomiendan: 72, dificultad: 2.1 },
  "LUNA BENOSO BENJAMIN": { calidad: 8.3, recomiendan: 83, dificultad: 44 },
  "SANCHEZ GARCIA LUZ MARIA": { calidad: 7.6, recomiendan: 69, dificultad: 1.5 },
  "AGUILAR GARCIA RAFAEL": { calidad: 7.7, recomiendan: 79, dificultad: 2.5 },
  "RODRIGUEZ CASTILLO MIGUEL ANGEL": { calidad: 8.9, recomiendan: 89, dificultad: 1.4 },
  "SANCHEZ JUAREZ JOSE": { calidad: 7.7, recomiendan: 100, dificultad: 0.7 },
  "SILVA MARTINEZ JORGE JAVIER": { calidad: 9.5, recomiendan: 94, dificultad: 1.3 },
  "CHAVEZ LIMA EDUARDO": { calidad: 6.6, recomiendan: 49, dificultad: 3.9 },
  "CARBALLO JIMENEZ JUAN MANUEL": { calidad: 8.6, recomiendan: 87, dificultad: 4.4 },
  "LOPEZ CARRERA BENJAMIN": { calidad: 6.6, recomiendan: 64, dificultad: 5.3 },
  "DIAZ TOALA IVAN": { calidad: 8.7, recomiendan: 85, dificultad: 3.3 },
  "TESTA NAVA ALEXIS": { calidad: 5.7, recomiendan: 45, dificultad: 5.1 },
  "PEREZ PEREZ JOSE JUAN": { calidad: 7.8, recomiendan: 75, dificultad: 1.5 },
  "HERNANDEZ SECUNDINO JOSE CELESTINO ELIAS": { calidad: 7.4, recomiendan: 67, dificultad: 1.3 },
  "ALCANTARA MENDEZ ALBERTO JESUS": { calidad: 7.9, recomiendan: 76, dificultad: 2 },
  "DURÀN CAMARILLO EDMUNDO RENÈ": { calidad: 6.4, recomiendan: 61, dificultad: 3.8 },
  "ALMAZAN FARFAN ROCIO": { calidad: 7.1, recomiendan: 66, dificultad: 4.2 },
  "CHAVARRIA BAEZ LORENA": { calidad: 6.1, recomiendan: 49, dificultad: 5.3 },
  "GALEANA CHAVEZ M. en A.P. MARIA DEL ROSARIO": { calidad: 9.3, recomiendan: 100, dificultad: 1.6 },
  "MELARA ABARCA REYNA ELIA": { calidad: 6.9, recomiendan: 53, dificultad: 2.2 },
  "VELEZ SALDAÑA ULISES": { calidad: 6.1, recomiendan: 47, dificultad: 5.7 },
  "AGUSTIN DOMINGUEZ VERONICA": { calidad: 9.3, recomiendan: 90, dificultad: 1.6 },
  "MENDOZA MACIAS ELBA": { calidad: 8.8, recomiendan: 88, dificultad: 3.5 },
  "JUAREZ MARTINEZ GENARO": { calidad: 6.9, recomiendan: 59, dificultad: 3.4 },
  "HURTADO AVILÉS GABRIEL": { calidad: 7.1, recomiendan: 69, dificultad: 2.6 },
  "CRUZ ROJAS JORGE ALBERTO": { calidad: 6.5, recomiendan: 56, dificultad: 1.1 },
  "CERVANTES ESPINOSA LUIS MOCTEZUMA": { calidad: 7.5, recomiendan: 77, dificultad: 3.3 },
  "MUJICA ASCENCIO CESAR": { calidad: 5.7, recomiendan: 47, dificultad: 4.6 },
  "GALICIA MEJIA RUBEN": { calidad: 6.2, recomiendan: 51, dificultad: 2.4 },
  "MARTINEZ DIAZ JUAN CARLOS": { calidad: 7.2, recomiendan: 66, dificultad: 4.6 },
  "CARRANZA CASTILLO OSCAR": { calidad: 9.2, recomiendan: 92, dificultad: 2.2 },
  "BAUTISTA ROSALES SANDRA IVETTE": { calidad: 4.9, recomiendan: 35, dificultad: 3.8 },
  "RIVERA DE LA ROSA MONICA": { calidad: 5.3, recomiendan: 57, dificultad: 1.8 },
  "ESCAMILLA MIRANDA PATRICIA": { calidad: 7.4, recomiendan: 65, dificultad: 2.2 },
  "CORTES GALICIA JORGE": { calidad: 9.5, recomiendan: 93, dificultad: 2.4 },
  "JUÁREZ MÉNDEZ ANA BELEM": { calidad: 8.5, recomiendan: 81, dificultad: 3.2 },
  "ORTIGOZA CAMPOS M. en C. ANDRES": { calidad: 8.4, recomiendan: 88, dificultad: 4.1 },
  "SANCHEZ BRITO MIGUEL": { calidad: 5.5, recomiendan: 25, dificultad: 5.7 },
  "LERMA MAGAÑA CARLOS": { calidad: 7.2, recomiendan: 50, dificultad: 0.7 },
  "CASTILLO CABRERA GELACIO": { calidad: 6.2, recomiendan: 56, dificultad: 3.2 },
  "GOMEZ MAYORGA MARGARITA ELIZABETH": { calidad: 4.3, recomiendan: 32, dificultad: 5 },
  "MORALES CRUZ JUAN CARLOS": { calidad: 7.5, recomiendan: 62, dificultad: 3.2 },
  "PASTRANA FERNANDEZ CARLOS JESUS": { calidad: 4.7, recomiendan: 30, dificultad: 4.5 },
  "ORTEGA GONZALEZ RUBEN": { calidad: 8.1, recomiendan: 73, dificultad: 5.4 },
  "TELLEZ BARRERA JUAN CARLOS": { calidad: 8.6, recomiendan: 82, dificultad: 2.1 },
  "PEREDO VALDERRAMA RUBEN": { calidad: 6.1, recomiendan: 50, dificultad: 4.2 },
  "ROJAS MEXICANO ISMAEL": { calidad: 6.8, recomiendan: 70, dificultad: 1 },
  "MALDONADO CASTILLO IDALIA": { calidad: 7.9, recomiendan: 83, dificultad: 3.9 },
  "RODRIGUEZ FLORES EDUARDO": { calidad: 8.5, recomiendan: 84, dificultad: 2.8 },
  "RODRIGUEZ ORDAZ MARISOL": { calidad: 6.3, recomiendan: 55, dificultad: 1.9 },
  "ALCARAZ TORRES JUAN JESUS": { calidad: 7.8, recomiendan: 79, dificultad: 1.4 },
  "SANCHEZ QUINTANILLA GILBERTO": { calidad: 6.1, recomiendan: 45, dificultad: 4.9 },
  "CORTEZ DUARTE NIDIA ASUNCIÓN": { calidad: 7.1, recomiendan: 66, dificultad: 3.1 },
  "ROMÁN GODÍNEZ RODRIGO FRANCISCO": { calidad: 7.3, recomiendan: 67, dificultad: 3.8 },
  "ROMERO HERRERA RODOLFO": { calidad: 5.9, recomiendan: 46, dificultad: 3.6 },
  "REYES VERA ABDIEL": { calidad: 6.3, recomiendan: 67, dificultad: 4 },
  "AGUILAR SANCHEZ FERNANDO": { calidad: 8.5, recomiendan: 86, dificultad: 1.8 },
  "MARQUEZ ARREGUIN GUILLERMO": { calidad: 7.6, recomiendan: 61, dificultad: 33 },
  "LOPEZ ROJAS ARIEL": { calidad: 9.5, recomiendan: 92, dificultad: 1.5 },
  "CORDERO LOPEZ MARTHA ROSA": { calidad: 6.1, recomiendan: 54, dificultad: 3 },
  "CIFUENTES ALVAREZ ALEJANDRO SIGFRIDO": { calidad: 5.4, recomiendan: 48, dificultad: 2.8 },
  "MORENO CERVANTES AXEL ERNESTO": { calidad: 9.3, recomiendan: 92, dificultad: 1.4 },
  "RODRIGUEZ SARABIA TANIA": { calidad: 5.2, recomiendan: 36, dificultad: 2 },
  "ALEMAN ARCE MIGUEL ANGEL": { calidad: 8.2, recomiendan: 100, dificultad: 1.3 },
  "GONZALEZ CISNEROS ALEJANDRO": { calidad: 6.0, recomiendan: 45, dificultad: 3.3 },
  "CARRETO ARELLANO CHADWICK": { calidad: 8.7, recomiendan: 89, dificultad: 1.8 },
  "CORONILLA CONTRERAS UKRANIO": { calidad: 6.5, recomiendan: 57, dificultad: 4.2 },
  "OJEDA SANTILLAN RODRIGO": { calidad: 3.2, recomiendan: 23, dificultad: 2.8 },
  "MARTINEZ ROSALES RICARDO": { calidad: 8.1, recomiendan: 89, dificultad: 2.9 },
  "TENORIO MARRON MARCO ANTONIO": { calidad: 9.3, recomiendan: 100, dificultad: 1.1 },
  "ENRIQUEZ ZARATE Dr. JOSE ASUNCION": { calidad: 8.3, recomiendan: 84, dificultad: 1.6 },
  "OCAMPO BOTELLO FABIOLA": { calidad: 6.7, recomiendan: 62, dificultad: 4.4 },
  "GUZMAN FLORES JESSIE PAULINA": { calidad: 6.2, recomiendan: 61, dificultad: 4.3 },
  "DIAZ SANTIAGO SANDRA": { calidad: 8.6, recomiendan: 88, dificultad: 3.6 },
  "CRUZ MEZA MARIA ELENA": { calidad: 5.9, recomiendan: 43, dificultad: 3.4 },
  "GONZALEZ ALBARRAN GISELA": { calidad: 7.9, recomiendan: 84, dificultad: 0.3 },
  "OLALDE MOGOLLAN NORMA": { calidad: 83.0, recomiendan: 88, dificultad: 0.2 },
  "SALDÍVAR ALMOREJO MARÍA MAGDALENA": { calidad: 2.4, recomiendan: 0, dificultad: 2.8 },
  "MALDONADO MUÑOZ MIGUEL ANGEL": { calidad: 8.4, recomiendan: 89, dificultad: 0.6 },
  "SOSA ADAN FANNY": { calidad: 8.8, recomiendan: 88, dificultad: 1.6 },
  "DORANTES CORDERO MARTHA MARGARITA": { calidad: 9.8, recomiendan: 100, dificultad: 0 },
  "LOYOLA ESPINOSA ARACELI": { calidad: 9.3, recomiendan: 100, dificultad: 0.7 },
  "DIAZ HUERTA CLAUDIA CELIA": { calidad: 8.1, recomiendan: 66, dificultad: 4.1 },
  "FLORES MERAZ YESICA SONIA": { calidad: 6.9, recomiendan: 58, dificultad: 5.2 },
  "ORTUÑO ARAUJO JESUS": { calidad: 8.3, recomiendan: 85, dificultad: 3.0 },
  "GONZALEZ CASTILLO JESUS ROBERTO": { calidad: 9.0, recomiendan: 83, dificultad: 2.5 },
  "JURADO JIMENEZ ROBERTO": { calidad: 6.1, recomiendan: 47, dificultad: 6.4 },
  "LEVARIO MEDINA SERGIO": { calidad: 6.1, recomiendan: 47, dificultad: 6.4 },
  "SOLORZA GUZMAN MISAEL": { calidad: 4.0, recomiendan: 11, dificultad: 5.7 },
  "GOMEZ TRESS MARIANA": { calidad: 10.0, recomiendan: 100, dificultad: 0.2 },
  "LAZCANO XOXOTLA LAURA": { calidad: 6.7, recomiendan: 68, dificultad: 1.6 },
  "WINFIELD REYES ANA MARIA": { calidad: 7.4, recomiendan: 73, dificultad: 2.3 },
  "CRUZ CARLIN EFREN": { calidad: 8.9, recomiendan: 89, dificultad: 2.0 },
  "MORALES RODRIGUEZ URSULA SAMANTHA": { calidad: 4.0, recomiendan: 23, dificultad: 5.0 },
  "RAMIREZ ROMERO TONAHTIU ARTURO": { calidad: 7.2, recomiendan: 63, dificultad: 4.1 },
  "RODRIGUEZ JORDAN GABRIEL DE JESUS": { calidad: 6.9, recomiendan: 50, dificultad: 2.3 },
  "SANTILLAN LUNA RAUL": { calidad: 7.6, recomiendan: 78, dificultad: 2.9 },
  "BUITRON DAMASO ISRAEL": { calidad: 5.6, recomiendan: 35, dificultad: 5.3 },
  "GUTIERREZ MEJIA DARWIN": { calidad: 9.1, recomiendan: 95, dificultad: 3.6 },
  "NAVA LARA JOEL": { calidad: 8.3, recomiendan: 86, dificultad: 3.2 },
  "SANTIAGO VALENTIN ERIC": { calidad: 8.9, recomiendan: 81, dificultad: 2.8 },
  "TIRADO LULE JUDITH MARGARITA": { calidad: 8.5, recomiendan: 81, dificultad: 4.8 },
  "CRUZ GARCIA DANIEL": { calidad: 5.5, recomiendan: 34, dificultad: 4.3 },
  "MOSCOSO MALAGON YOSAFAT": { calidad: 6.9, recomiendan: 54, dificultad: 2.3 },
  "JUAREZ LEON CARLOS": { calidad: 4.4, recomiendan: 24, dificultad: 6.1 },
  "ZARATE CARDENAS ALEJANDRO": { calidad: 7.4, recomiendan: 86, dificultad: 1.0 },
  "CABRERA CHAVEZ GLORIA LOURDES": { calidad: 8.5, recomiendan: 88, dificultad: 1.5 },
  "MARTINEZ PERALES JOSE CRUZ": { calidad: 7.4, recomiendan: 73, dificultad: 1.6 },
  "VILLEGAS NAVARRETE SONIA": { calidad: 8.4, recomiendan: 86, dificultad: 2.0 },
  "DOMINGUEZ HERNANDEZ SAMUEL": { calidad: 7.4, recomiendan: 78, dificultad: 2.2 },
  "ESQUIVEL CENTENO JOSE ARMANDO": { calidad: 8.3, recomiendan: 85, dificultad: 1.4 },
  "GARCIA FLORIANO ANDRES": { calidad: 9.9, recomiendan: 100, dificultad: 0.4 },
  "SALINAS CALLEJAS MARÍA DE LOURDES": { calidad: 8.2, recomiendan: 100, dificultad: 0.0 },
  "MARTINEZ GUERRERO JOSE ALFREDO": { calidad: 6.1, recomiendan: 61, dificultad: 3.5 },
  "VAZQUEZ ORTIZ MIJAIL": { calidad: 7.6, recomiendan: 75, dificultad: 3.8 },
  "SALAZAR RAMIREZ MANUEL": { calidad: 7.8, recomiendan: 81, dificultad: 2.8 },
  "FLORES DELGADO RAQUEL": { calidad: 6.5, recomiendan: 66, dificultad: 0.7 },
  "JIMENEZ GALAN YASMIN IVETTE": { calidad: 7.9, recomiendan: 81, dificultad: 2.6 },
  "BARRON VERA JOSUE EMANUEL": { calidad: 6.7, recomiendan: 46, dificultad: 4.3 },
  "LOPEZ LEYVA LUIS OCTAVIO": { calidad: 6.8, recomiendan: 60, dificultad: 4.6 },
  "CORTÉS DÁVALOS ANDRÉS": { calidad: 7.5, recomiendan: 50, dificultad: 3.0 },
  "GARCIA SALES JUAN VICENTE": { calidad: 7.8, recomiendan: 62, dificultad: 1.9 },
  "BARRALES LOPEZ ANA LUZ": { calidad: 4.2, recomiendan: 14, dificultad: 5.7 },
  "FERNANDEZ VAZQUEZ ALFONSO": { calidad: 7.2, recomiendan: 67, dificultad: 5.3 },
  "JIMENEZ RUIZ RENE BALTAZAR": { calidad: 7.2, recomiendan: 67, dificultad: 5.3 },
  "LINARES VALLEJO ERICK EUGENIO": { calidad: 6.4, recomiendan: 51, dificultad: 4.1 },
  "HERNANDEZ AGUILAR JOSE LUIS": { calidad: 7.4, recomiendan: 74, dificultad: 4.0 },
  "LEON HERNANDEZ MIGUEL ABEL": { calidad: 7.0, recomiendan: 54, dificultad: 4.5 },
  "MARTINEZ NUÑO JESUS ALFREDO": { calidad: 6.1, recomiendan: 61, dificultad: 4.7 },
  "MANZANILLA GRANADOS HECTOR MANUEL": { calidad: 5.8, recomiendan: 48, dificultad: 3.8 },
  "MONTIEL SANCHEZ ANGEL SALVADOR": { calidad: 7.4, recomiendan: 68, dificultad: 4.1 },
  "JIMENEZ BENITEZ JOSE ALFREDO": { calidad: 8.2, recomiendan: 78, dificultad: 1.7 },
  "PEREZ DE LOS SANTOS MONDRAGON TANIBET": { calidad: 5.8, recomiendan: 46, dificultad: 4.0 },
  "MORALES GUITRON SANDRA LUZ": { calidad: 5.0, recomiendan: 40, dificultad: 2.7 },
  "ORTIZ RAMIREZ JOSE ANTONIO": { calidad: 8.6, recomiendan: 89, dificultad: 1.1 },
  "SOTO RAMOS MANUEL ALEJANDRO": { calidad: 7.3, recomiendan: 78, dificultad: 2.8 },
  "CAMACHO VAZQUEZ VANESSA ALEJANDRA": { calidad: 7.7, recomiendan: 83, dificultad: 0.2 },
  "BLANCO ALMAZAN IVAN EDUARDO": { calidad: 7.8, recomiendan: 83, dificultad: 3.2 },
  "CASTILLO MARTÍNEZ MIGUEL ÁNGEL": { calidad: 6.5, recomiendan: 71, dificultad: 4.6 },
  "HERNANDEZ OLVERA LUIS ENRIQUE": { calidad: 6.9, recomiendan: 50, dificultad: 3.9 },
  "CALDERON SAMBARINO MARIA JULIA": { calidad: 8.6, recomiendan: 81, dificultad: 3.7 },
  "SILVA SANCHEZ CARLOS": { calidad: 6.8, recomiendan: 44, dificultad: 4.9 },
  "CERVANTES DE ANDA ISMAEL": { calidad: 8.7, recomiendan: 86, dificultad: 2.9 },
  "ARZATE GORDILLO JACQUELINE": { calidad: 8.3, recomiendan: 80, dificultad: 3.8 },
  "PUEBLA LOMAS JAIME HUGO": { calidad: 6.3, recomiendan: 52, dificultad: 3.9 },
  "HENESTROSA CARRASCO LETICIA": { calidad: 8.4, recomiendan: 84, dificultad: 3.5 },
  "PALMA OROZCO ROSAURA": { calidad: 7.6, recomiendan: 70, dificultad: 1.5 },
  "GONZALEZ RAMIREZ MARKO ALFONSO": { calidad: 7.3, recomiendan: 44, dificultad: 2.4 },
  "ORTIZ CASTILLO MARCO ANTONIO": { calidad: 8.3, recomiendan: 80, dificultad: 2.6 },
  "MEDINA MEJIA VIRGINIA": { calidad: 9.4, recomiendan: 96, dificultad: 0.5 },
  "ROSAS CARRILLO ARY SHARED": { calidad: 7.2, recomiendan: 67, dificultad: 1.7 },
  "GASPAR MEDINA FABIAN": { calidad: 8.7, recomiendan: 79, dificultad: 1.7 },
  "NÚÑEZ PRADO CÉSAR JESÚS": { calidad: 9.5, recomiendan: 100, dificultad: 3.8 },
  "PALACIOS SOLANO ROCIO": { calidad: 7.5, recomiendan: 71, dificultad: 3.6 },
  "PINEDA GUERRERO CARLOS": { calidad: 8.1, recomiendan: 82, dificultad: 3.3 },
};
